### ISSUE TITLE
Soft wrap lines and auto refresh

### ISSUE THREAD

**Issue by derevyan** [amir20/dozzle#3278] opened 2024-09-16 06:37 UTC
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.4.3

### ✅ Command used to run Dozzle

docker compose start

### 🐛 Describe the bug / provide steps to reproduce it

During enabled `Soft wrap lines` auto refresh make Chrome browser main log window screen jumps up and down for few lines that makes it very hard to monitor. 

Thanks a lot for a great tool!

### 💻 Environment

Client: Docker Engine - Community
 Version:    27.1.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.25.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 45
  Running: 43
  Paused: 0
  Stopped: 2
 Images: 97
 Server Version: 27.1.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-101-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.13GiB
 Name: ns536019
 ID: 50038232-2b79-436f-913e-bc1757b6c8de
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: rootsapp
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by amir20** [comment] 2024-09-16 14:01
Hey, I use chrome everyday and never noticed this. Soft wrap is enabled by default so I would expect others to see this too. 

Can you record a video? 

I am not sure what you mean by jumping.

**Comment by amir20** [comment] 2024-09-16 18:49
Oh I see so this showing the horizontal scroll bar? I probably don't see this because I am on a Mac. 

I'll have to see if I can reproduce this.

**Comment by amir20** [comment] 2024-09-16 18:51
oh interesting. I was able to reproduce this on mac by trying to scroll. This was introduced when I added the animation at the bottom.

**Comment by toast-ts** [comment] 2024-09-17 06:27
That PR patch seems to resolves the distracting issue for me.

**Comment by amir20** [comment] 2024-09-17 13:18
Thanks! I have merged in master. Will push a build today.

**Comment by amir20** [comment] 2024-09-17 20:57
This is fixed now. You all should confirm on other browsers.

**Closed** 2024-09-17 20:57 UTC
Labels: bug

**Comment by amir20** [comment] 2024-09-20 16:06
@derevyan Did this work? Please confirm.
