### ISSUE TITLE
[Feature Request] See host name in main table

### ISSUE THREAD

**Issue by twist3dimages** [amir20/dozzle#2362] opened 2023-08-23 22:40 UTC
**Is your feature request related to a problem? Please describe.**
Sort of a problem, in my case, I am not sure which container is having high CPU usage (they are named the same) but I have 2 docker hosts. Even when I click on the container, I still don't know which one is having high CPU usage
![image](https://github.com/amir20/dozzle/assets/33134502/8a2f0876-e91e-45bf-9825-8afdeb4ca4ad)
![image](https://github.com/amir20/dozzle/assets/33134502/c9a299e5-fe17-41fb-ade7-da91a3ac7b36)

**Describe the solution you'd like**
Another column on this page to let me know what host/IP is running the container on this screen
![image](https://github.com/amir20/dozzle/assets/33134502/34cd13f3-7819-4ebc-a1e2-0e39afa99bf7)

some indication on this screen as well

![image](https://github.com/amir20/dozzle/assets/33134502/26d37921-14a4-4874-acf8-a2dcd78be07d)

maybe it can be optional?
**Describe alternatives you've considered**
See above

**Additional context**
see above

**Comment by amir20** [comment] 2023-08-23 23:49
First, 98 containers. Wow! You should be testing more often to make sure I don't break things. 

It shows that Dozzle is consuming over 100% CPU.  What's going on there? I have battle tested with 60+ containers but never seen it that much CPU. Is there something going on your env? I wonder if I can reproduce it on my side and what is causing such high CPU.  If you have a lot remote containers, that could cause it. But I am just guessing. 

Finally, I think your feature request makes sense. On the homepage, a new column is easy. I'll add that. On the container page, I think I'll do `HOST / CONTAINER_NAME`. Let me know if you have better ideas there. 

I would love to see why Dozzle is consuming so much CPU for you. I have never seen it that hight.

**Comment by twist3dimages** [comment] 2023-08-24 22:21
Hahaha I went a little out of hand on my Unraid server! I use CPU pinning on my main machine so it doesn't take too much CPU usage. I had an issue where I was getting insane CPU usage and I think it's because I have 2 appdata folders so it was going a little crazy. The 100% is it basically saying it's taking 100% of the cores I've told it to

> Finally, I think your feature request makes sense. On the homepage, a new column is easy. I'll add that. On the container page, I think I'll do HOST / CONTAINER_NAME. Let me know if you have better ideas there.

Sounds great to me!

> I would love to see why Dozzle is consuming so much CPU for you. I have never seen it that hight.
I will say one thing I have noticed is the sometimes the logs are completely blank and then other times it will show me logs from other containers. For example, I'll look at redis, then move to postgres, but the top part of the logs still have some of the redis logs.
I will see if I can find a screenshot for it but it's not that common that it happens. If there are any logs I can provide let me know

**Comment by amir20** [comment] 2023-08-24 22:47
Weird, I just tested 100+ containers at a cool 5% CPU. Not sure what is happening with your Dozzle to need so much CPU. Most of it just reading the stats from Docker converting to JSON. Not much else is going on. 

> because I have 2 appdata folders so it was going a little crazy.

What does that mean? 

I usually pin my containers with memory. I just never seen Dozzle take this much resources. If you can think of a way for me to reproduce, let me know.

**Comment by twist3dimages** [comment] 2023-08-25 01:14
so i have 2 drives mounted at 

/mnt/ssd/appdata
/mnt/cache/appdata

if I say /mnt/user/appdata (what it was), it is looking/saving to directories from two different drives. basically it's searching two drives for the application files


also i managed to get a screenshot of it including logs from another container

![image](https://github.com/amir20/dozzle/assets/33134502/b797d0aa-9e1f-493d-9ede-9a5260fd3684)

**Comment by twist3dimages** [comment] 2023-08-25 01:16
> I usually pin my containers with memory. I just never seen Dozzle take this much resources. If you can think of a way for me to reproduce, let me know.

it's only taking 27 MB of memory now with two hosts, what you saw was it taking 100% of 1 or 2 CPU cores, not 100% of 24 cores

this is the average CPU usage now
![image](https://github.com/amir20/dozzle/assets/33134502/53174759-a224-43a4-932c-4c0f5a01fe6a)

**Comment by amir20** [comment] 2023-08-25 16:54
Ah ok good to know. Even with 100s of containers I think Dozzle should only hit about 5%. I'll stop testing the memory and CPU. 

I should have the new column on the homepage ready. Container page is a little trickier because of space.

**Comment by amir20** [comment] 2023-08-25 17:21
#2367 is the PR for homepage

**Comment by twist3dimages** [comment] 2023-08-25 19:48
Hey btw, what does this mean? 
![image](https://github.com/amir20/dozzle/assets/33134502/c8bb4b1b-a8a8-4069-949d-dade6ddfae55)

I am getting some heavy CPU usage, not sure if that's something with Dozzle or a container. I use docker socket proxy on both hosts and for the remote hosts environment variable, i used /var/run/docker.sock for my local container. Do you think it's because I needed to add it in the remote hosts?

also, i do not have these environment variables set, but am getting a message about it. what do they do?

![image](https://github.com/amir20/dozzle/assets/33134502/15671c26-3f54-46b8-8e56-bca6353da1d9)

**Comment by twist3dimages** [comment] 2023-08-25 19:50
> #2367 is the PR for homepage

love it! perfect! thank you!

**Comment by twist3dimages** [comment] 2023-08-25 20:32
one thing I did notice is on the left, it's not alphabetical (which is fine)

![image](https://github.com/amir20/dozzle/assets/33134502/231f66ce-580a-4817-b0e7-1f4992d13079)


Just to make it more clarifying, do you think something like a header with the hostname separating them would make sense? like a grouping header?

**Comment by amir20** [comment] 2023-08-25 20:32
> Hey btw, what does this mean?

Those are errors by Docker. Not Dozzle errors. I think (just guessing) when Docker API throws errors they just get bubbled up to the clients. 

> I am getting some heavy CPU usage, not sure if that's something with Dozzle or a container. I use docker socket proxy on both hosts and for the remote hosts environment variable, i used /var/run/docker.sock for my local container. Do you think it's because I needed to add it in the remote hosts?

I do something similar with very little CPU. It's weird that Dozzle itself is reporting high CPU usage which means that Dozzle application could be doing something CPU intensive. I don't know what is causing it. Couple questions: 

1. Does Dozzle show high CPU even when there aren't any tabs open? You can test with `docker stats`
2. Do you usually have multiple tabs open? 
3. If you only have single localhost is it still high CPU?  

> also, i do not have these environment variables set, but am getting a message about it. what do they do?

Are you sure? You probably had set those env var before. They are old env variables which are not used anymore. You might have copied it from an old docker compose file.

**Comment by amir20** [comment] 2023-08-25 20:41
> one thing I did notice is on the left, it's not alphabetical (which is fine)

Um, it should be sorted by name. If not then maybe a bug. 

> Just to make it more clarifying, do you think something like a header with the hostname separating them would make sense? like a grouping header?

You should only be able to see one host at a time on the left. So I am not sure what you mean.

**Comment by amir20** [comment] 2023-08-25 20:41
#2369 should fix a few more bugs on hosts.

**Comment by amir20** [comment] 2023-08-25 22:22
I think I can close this as the original goal of getting host names more visible is done. 

For any other bugs, we can create a new issue.

**Closed by amir20** 2023-08-25 22:22 UTC
Labels: enhancement
