### ISSUE TITLE
New option for time format (12 / 24 h)

### ISSUE THREAD

**Issue by jo-me** [amir20/dozzle#523] opened 2020-06-18 11:12 UTC
**Is your feature request related to a problem? Please describe.**
The time format is fixed to 12h format which does not match many users' locale. 
Normally you can change that in an app from 12h to 24h.

**Describe the solution you'd like**
A new option to specify the time format (12h / 24h)

**Describe alternatives you've considered**
n/a

**Additional context**

![image](https://user-images.githubusercontent.com/10351272/85013738-5ee37680-b165-11ea-83c5-8cac69313d38.png)

**Comment by amir20** [comment] 2020-06-18 19:14
Hello. This is a duplicate of https://github.com/amir20/dozzle/issues/502. Sounds like it's important for many folks. 

I could use some help. I see you have a lot of Javascript expertise. :) 

`date-fns` suggests doing something like https://github.com/date-fns/date-fns/issues/1218#issuecomment-599182307. But that seems like an over kill. 

I also don't want to include all kind of different locales in Dozzle. 

Would you be able to help?

**Comment by amir20** [comment] 2020-06-18 20:41
@jo-me can you open your browser's console and run `navigator.language`. I think I found a solution, but instead of having a toggle to 12h/24h I think it can be automated via browser's language.

**Comment by jo-me** [comment] 2020-06-18 20:52
Hi,
as far as I can see you're using the library without any options, so the default locale (en-US) is used which produces the AM/PM format in the formatRelative function.
So you could specify the users' locale to the library and hope for the best or implement a (several) hardcoded formats into it, right?

I personally would be fine with just the output of JS's date.toISOString():
```
new Date().toISOString()
"2020-06-18T20:47:06.143Z"
```
or something similar. The long date format with "today"/"yesterday"/"last week" and missing seconds or even milliseconds is not precise anyway.

So back to your question, my locale according to chrome is:

```
navigator.language
"de-DE"
```

**Comment by amir20** [comment] 2020-06-18 21:04
Thanks. 

I think I found a fix with https://github.com/amir20/dozzle/pull/525/files#diff-1844870392c26ecc5ef974c1f726fa1cR9-R14. 

I am going to merge and have you try `latest-dev`

**Comment by jo-me** [comment] 2020-06-18 21:29
Seems to work :
![image](https://user-images.githubusercontent.com/10351272/85073496-2cfcff00-b1bb-11ea-908d-f4351188b2aa.png)

Thanks for your effort!

**Comment by amir20** [comment] 2020-06-18 21:34
Sounds good. Yw.

**Comment by amir20** [comment] 2020-06-18 21:34
I will release a new official release today.

**Closed by amir20** 2020-06-18 21:34 UTC
Labels: enhancement

**Comment by fabianomg** [comment] 2021-08-24 02:50
date 24h/12h date-fns:  format(utcToZonedTime(new Date(), 'America/Sao_Paulo'),'dd-MM-yyyy HH:mm' )
HH = 24h hh =12h
