### ISSUE TITLE
 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Hige** [amir20/dozzle#875] opened 2020-12-07 09:02 UTC
Hello.
Launched 350 containers. Faced such a problem. The Dozzle container breaks every 2 minutes. The log is given below.

Help please.

```
today at 11:48  level=info msg="Dozzle version v3.0.3"
today at 11:48  level=info msg="Accepting connections on :8080"
today at 11:51  panic: runtime error: invalid memory address or nil pointer dereference
today at 11:51  [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x490f82]
today at 11:51  
today at 11:51  goroutine 4943 [running]:
today at 11:51  bufio.(*Writer).Flush(0xc0001e0100, 0xc001f20000, 0x7e0)
today at 11:51    /usr/local/go/src/bufio/bufio.go:607 +0x62
today at 11:51  bufio.(*Writer).Write(0xc0001e0100, 0xc001f20000, 0x20975, 0x31fe1, 0x750100, 0xc000f5fd48, 0x76192f)
today at 11:51    /usr/local/go/src/bufio/bufio.go:643 +0xfc
today at 11:51  net/http.(*response).write(0xc00033e2a0, 0x20975, 0xc001f20000, 0x20975, 0x31fe1, 0x0, 0x0, 0xc0000dd120, 0xc000f5fe50, 0xbe70b8)
today at 11:51    /usr/local/go/src/net/http/server.go:1607 +0x30a
today at 11:51  net/http.(*response).Write(0xc00033e2a0, 0xc001f20000, 0x20975, 0x31fe1, 0x0, 0x0, 0xc001efe000)
today at 11:51    /usr/local/go/src/net/http/server.go:1565 +0x56
today at 11:51  encoding/json.(*Encoder).Encode(0xc000f5ff28, 0xa99dc0, 0xc0000dd120, 0xc0000dd120, 0xc00033e2a0)
today at 11:51    /usr/local/go/src/encoding/json/stream.go:231 +0x1cb
today at 11:51  main.sendContainersJSON(0xc937c0, 0xc000267860, 0xc8efc0, 0xc00033e2a0, 0xbe9298, 0xc0000d1d50)
today at 11:51    /dozzle/routes.go:240 +0x1b7
today at 11:51  main.(*handler).streamEvents.func1()
today at 11:51    /dozzle/routes.go:211 +0x4c
today at 11:51  created by time.goFunc
today at 11:51    /usr/local/go/src/time/sleep.go:167 +0x45
today at 11:51  level=info msg="Dozzle version v3.0.3"
today at 11:51  level=info msg="Accepting connections on :8080"
```

**Comment by amir20** [comment] 2020-12-07 22:28
I have never launched 350 containers. I imagine listening for all CPU and memory changes can create a memory issue. 

Do you really need 350 containers or were you just testing?

**Comment by amir20** [comment] 2020-12-10 19:52
I was able to reproduce this with 200+ containers. However, when I measured dozzle memory for only 100 conainters, it only jumped from 10MB to 16MB. So most likely, this is not Dozzle's memory issue. With 200 containers, my machine just ran out of memory. And it seems like from the error, you are having memory issue.

I am closing this as it is not related to Dozzle. If you can take a screenshot of how much memory Dozzle is using and find it to be be a lot then I can keep investigating. Here is a screenshot with 120 containers. 

<img width="2032" alt="Screen Shot 2020-12-10 at 11 51 00 AM" src="https://user-images.githubusercontent.com/260667/101822395-1b4b4300-3ade-11eb-84e8-4866c46c2feb.png">

**Comment by Hige** [comment] 2020-12-11 10:31
Yes, we really need that many containers. We create many test environments.
We would like to use dozzle to read logs.

I think the problem is in the dozzle. There is a memory leak somewhere.

I am attaching screenshots showing that 40+ GB of free memory is available

Thanks


![Screenshot_20201211_131946](https://user-images.githubusercontent.com/1768871/101891852-a4807980-3bb3-11eb-994a-cfd8ddcd8e83.png)
![Screenshot_20201211_132808](https://user-images.githubusercontent.com/1768871/101892705-c3cbd680-3bb4-11eb-9475-9bd9daee2f3b.png)
![Screenshot_20201211_132746](https://user-images.githubusercontent.com/1768871/101892706-c4646d00-3bb4-11eb-8ad8-89dfc77af3c3.png)

**Comment by amir20** [comment] 2020-12-11 13:58
Free memory doesn’t mean anything. It depends how much memory is free to docker. 

Like I asked earlier, Do you know how much memory is dozzle using?

Sent via my iPhone

**Comment by amir20** [comment] 2020-12-11 14:04
According to your screenshot, dozzle is only using 43MB mem.

**Comment by Hige** [comment] 2020-12-11 16:07
Docker has access to all free memory.

From the api dozzle it is clear that memory is consumed differently at different times. There are jumps, as in the screenshot 3596.5GB
I think there is a memory leak somewhere.
Please check. How can I help you find and isolate the problem?

![Screenshot_20201211_190307](https://user-images.githubusercontent.com/1768871/101926114-d01b5800-3be3-11eb-8ae7-2407966b12e4.png)

**Comment by amir20** [comment] 2020-12-11 16:19
That is concerning if it’s true. I need to research. 

How many users are using Dozzle at the same time?

**Comment by Hige** [comment] 2020-12-11 16:27
We did not distribute this URL. The resource is closed by vpn. At the moment, only I have used. (1 user)

**Comment by amir20** [comment] 2020-12-11 21:41
I was able to reproduce this. But it doesn't look like it is related to memory actually. There seems to be a problem when a lot of containers are being added. 

@Hige if I send you a patch, can you try it out by compiling dozzle? 

Meanwhile, please add `--level debug` to your container.

**Comment by amir20** [comment] 2020-12-13 18:07
@Hige, I tried a lot of time debugging this issue. Looks like there are three separate issues that are not related to each other. 

1. The stacktrace you posted for this issue `panic: runtime error: invalid memory address or nil pointer dereference` seems to be related to race condition. I have removed that race condition. Can you try `amir20/dozzle:latest-dev` which is dev build from master? 
2. I investigated the memory issue. I still cannot reproduce it. With 500+ containers, I was only able to get to 60MB. The memory didn't drop but even when I tried to use multiple clients, it did hover around 60MB. 
3. Docker API has a bug https://github.com/moby/moby/issues/35888 which I noticed with 200+ containers. This only happened <1% for me. 

Please try the latest dev build. I'll need more help from you with `--level debug` to understand what is going on with memory.

**Comment by Hige** [comment] 2020-12-14 08:08
Thanks for tackling this issue.

I am attaching a debug log.

[debug.log](https://github.com/amir20/dozzle/files/5687313/debug.log)

**Comment by amir20** [comment] 2020-12-14 15:22
Did you try the new build?

**Comment by Hige** [comment] 2020-12-15 10:48
Yes. I used build amir20/dozzle:latest-dev

![Screenshot_20201215_133530](https://user-images.githubusercontent.com/1768871/102205410-3651f480-3edc-11eb-969c-7829ee57c5eb.png)

**Comment by amir20** [comment] 2020-12-15 14:46
How is the new build? Do you still see the panic? What about memory?

**Comment by Hige** [comment] 2020-12-15 17:26
I have attached the log file above.
Unfortunately, the situation has not changed, I can still see panic. Memory consumption is high.

:(

**Comment by amir20** [comment] 2020-12-15 18:16
Hi @Hige, I looked at the logs again and didn't see the panic that was listed in this issue. The one you are seeing `FIXME: Got an status-code for which error does not match any expected type!!!: -1` module=api status_code=-1` is related to the docker bug. I have looked at it and it is not related to Dozzle. 

For the memory issue, I can't spend more time on it because I have yet to be able to reproduce it. I'll need your help. I was able to install pprof which is a memory profiler. You can see the branch at https://github.com/amir20/dozzle/tree/pprof. Pull the branch and do `docker build -t amir20/dozzle:pprof .` and use that image instead. 

Wait until the memory is high, and do `curl http://hostname/debug/pprof/heap`. Send me that file. 

Thanks.

**Comment by amir20** [comment] 2020-12-17 03:00
I am closing. I don't plan to work on this and I cannot reproduce memory issues. I have modified master to print more debugging info for memory. See https://github.com/amir20/dozzle/pull/898/files#diff-a622ec57ed116d8a455b361a3262529f16dff90edf295c5943e8f0a3c836e5d0R167-R173

**Closed by amir20** 2020-12-17 03:00 UTC
Labels: bug
