### ISSUE TITLE
Infinite load for a specific container

### ISSUE THREAD

**Issue by FrancYescO** [amir20/dozzle#3385] opened 2024-11-13 08:30 UTC
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

8.7.5

### ✅ Command used to run Dozzle

as doc

### 🐛 Describe the bug / provide steps to reproduce it

i have a specific container that does not load logs, is like the same infinite load as if you set a log filter that have no result, or if a container have a 0b of logs (can we fix also these 2cases and get the loading bar instead of spinner if /stream endpoint connection is fullfilled? :D)... but in this case the logs are populated just the /stream api returns empty

going backward with versions i noticed the bug popups in >=v7.0.5 while v7.0.4 correctly loads the logs of this container

for reference is what i posted here https://github.com/amir20/dozzle/issues/3222#issuecomment-2471564111

all other container on the same host shows no issue, so i assume is something in the content of logs that breaks things, (is a pretty standard nginx log output)... this is how it ends actually:

```
...
2023-06-01T13:42:08.858573533Z 172.18.0.13 - - [01/Jun/2023:13:42:08 +0000] "GET /api/rpc/command/get-file-libraries?file-id=3b37f927-c632-809f-8002-67f1ddd6fbf5&features=storage/pointer-map HTTP/1.1" 200 113778 "-" "Mozilla/5.0 (X11; Linux x86_64) Chrome/113.0.0.0 Safari/537.36"
2023-09-21T10:01:32.969509513Z 2023/09/21 10:01:26 [emerg] 1#1: host not found in upstream "penpot-backend" in /etc/nginx/nginx.conf:85
2023-09-21T10:01:33.372310975Z nginx: [emerg] host not found in upstream "penpot-backend" in /etc/nginx/nginx.conf:85
2023-10-03T09:02:23.994639918Z 2023/10/03 09:02:23 [emerg] 1#1: host not found in upstream "penpot-backend" in /etc/nginx/nginx.conf:85
2023-10-03T09:02:24.415120539Z nginx: [emerg] host not found in upstream "penpot-backend" in /etc/nginx/nginx.conf:85
```

### 💻 Environment

-

**Comment by amir20** [comment] 2024-11-13 16:36
I reviewed the differences between versions 7.0.4 and 7.0.5 at https://github.com/amir20/dozzle/compare/v7.0.4...v7.0.5. One thing stood out: in version 7.0.5, I follow containers and only stream logs since the container started. This change prevents old logs from appearing when containers are restarted. I doubt this is the source of the problem.

I need a way to reproduce this issue on my end.

1. How are you starting Nginx?  
2. If you create a dummy Nginx instance, does the same issue occur?  
3. Have you confirmed that no filters, log levels, or stdout/stderr toggles are set?  
4. What does the API endpoint `/stream` return?  

I can't think of anything else.

**Comment by FrancYescO** [comment] 2024-11-13 20:56
1)
is not a vanilla nginx is the one embedded in the frontend of this stack: https://github.com/penpot/penpot/blob/develop/docker/images/docker-compose.yaml runned via portainer and with restart: unless-stopped instead of always
2)
No. i have ~30services on this host only this container have this issue
3)
Sure.
4)
After ~6s just pings `:ping`

**Comment by amir20** [comment] 2024-11-14 00:34
I am stumped on this one. Seems like your frontend container is based off `nginxinc/nginx-unprivileged`. `docker run nginxinc/nginx-unprivileged` seems to work with Dozzle. 

Not sure what can be done to debug. Maybe completely destroy the container and recreate it.

**Comment by FrancYescO** [comment] 2024-11-15 23:44
i've recreated the container and the bug (but also older logs :D) disappeared, so actually i have no way to replicate we don't know the culprit but maybe we can just close this isse....

**Comment by FrancYescO** [comment] 2024-11-18 11:33
i reuse this issue but i'm not sure this is the same bug ... today with 8.8.0 i was trying to see log of a specific container but figured out that it was searching for logs of wrong-destroyed container id:

i got my container id e9fbd40f2b29 running than deployed a new image via portainer, so the container e9fbd40f2b29 got stopped and restarted with a new id 20c05b0abb96, dozzle did not switched to the new container and **also after refreshing the page/clearing cache** looks like was still seeing the old id e9fbd40f2b29 as running (but with no logs)

each click on the container in the sidebar result in dozzle logs says that the containerid was not found but in the webpage the "Container not found" message did not show (was just loading a few sec than shows no log, not the same as if you put a non-existent id in the URL)

recreating the container did not help, restarting dozzle container the issue.... is there some sort of cache somewhere?

**Comment by amir20** [comment] 2024-11-18 16:03
Hey @FrancYescO,

I haven't seen this issue personally. Someone else created it a while back, but I can't find it right now. I'll need your help to debug. If I can't reproduce the issue, it will be difficult to fix.

Yes, Dozzle has an internal "store" that caches and stores all statistics for containers. It usually works well. I listen for specific Docker events to update the internal store.

It seems like there might be an issue with Portainer, as the other case I remember was similar.

Can you try to reproduce this state again? If you can consistently get into this state, it would be helpful to enable `DEBUG` logs for Dozzle and also keep `docker system events` open while this is happening.

Most likely, some unusual event is occurring, and Dozzle isn't refreshing its own store.

Thanks!

**Comment by FrancYescO** [comment] 2024-11-18 17:22
i'll keep an eye on it to find a way to easily reproduce... surely i can say that seems is the first time i've seen the issue and my deployment was ever done in the same way

> listen for specific Docker events

at what events are you listening for destroy and recreate? ... maybe there is some edge-case event the is getting ignored

**Comment by FrancYescO** [comment] 2024-11-19 19:24
Btw just happened again...

I'll keep trying to isolate the issue but pretty sure is something with portainer webhook redeploy (or recreate?) methods

**Comment by FrancYescO** [comment] 2024-11-20 11:28
i'm not 100% sure but this should be an extract during that bug happend .. maybe we miss kill? or the rename after kill-stop-die-destroy do some magic ?

```
...
2024-11-20T10:41:24.091811116+01:00 container start 3dfb999250d09ac1894a98fdb690c87e16bd9a344dd72b2491c9a437e804ef18
2024-11-20T10:41:24.984085411+01:00 container die 3dfb999250d09ac1894a98fdb690c87e16bd9a344dd72b2491c9a437e804ef18
2024-11-20T10:41:57.305370996+01:00 image pull registry.org/image:latest
2024-11-20T10:41:57.418400610+01:00 container create 6e5d2f7db6f5a8b2d1b0ae6a42aed70dbb7f039fb51a79599e274e2d4b5f98b4
2024-11-20T10:41:57.436166302+01:00 container kill 21a85032fee12773a36b060f769dc7b5c7ad72af0342333abb7642d2d9eef6a9
2024-11-20T10:41:58.120718193+01:00 container stop 21a85032fee12773a36b060f769dc7b5c7ad72af0342333abb7642d2d9eef6a9
2024-11-20T10:41:58.125265685+01:00 container die 21a85032fee12773a36b060f769dc7b5c7ad72af0342333abb7642d2d9eef6a9
2024-11-20T10:41:58.136485321+01:00 container destroy 21a85032fee12773a36b060f769dc7b5c7ad72af0342333abb7642d2d9eef6a9
2024-11-20T10:41:58.145454536+01:00 container rename 6e5d2f7db6f5a8b2d1b0ae6a42aed70dbb7f039fb51a79599e274e2d4b5f98b4
2024-11-20T10:41:58.729965699+01:00 container start e05e623c2858e120bb9e5b5222068ea34bcfd13fb1060126ca5d0b2d84d57a1a
2024-11-20T10:41:58.804224198+01:00 container start 6e5d2f7db6f5a8b2d1b0ae6a42aed70dbb7f039fb51a79599e274e2d4b5f98b4
2024-11-20T10:42:24.500759429+01:00 container start 3dfb999250d09ac1894a98fdb690c87e16bd9a344dd72b2491c9a437e804ef18
2024-11-20T10:42:24.823076718+01:00 container die 3dfb999250d09ac1894a98fdb690c87e16bd9a344dd72b2491c9a437e804ef18
...
```

**Comment by amir20** [comment] 2024-11-20 18:31
Hmmm....

I don't see anything wrong here. I see two containers. The one starting `21` and the other with `6e`. 

1. `6e` gets created. This event is ignored by Dozzle. 
2. Then renamed. Which gets picked up but ignored because Dozzle never picked up the created event. 
3. Then `start`ed which should be handled correclty. 

And then other container: 

1. Container `21` get killed. Which is ignored. `stop`ed which is ignored. 
2. `die` should be picked up. 
3. And finally `destroy` should remove it. 

One thing you can do is run with `--level trace` for Dozzle. You should see something like "event=.... received container event" which output all the events Dozzle sees. 

Perhaps compare those with `system events`. There might be something else happening. How are you getting to this state? I tried setting a Portainer a while ago but it just seemed more complicated and I couldn't figure out how to use it properly.

**Comment by FrancYescO** [comment] 2024-11-20 18:59
It happened 2times during a stack update via portainer webhook (you should register at least a free account for the business edition)

But this happens various time during the day and all keeps working correctly so I'm still not able to find an easy replicable path...

**Comment by amir20** [comment] 2024-11-20 19:20
> But this happens various time during the day and all keeps working correctly so I'm still not able to find an easy replicable path.

I wonder if this is a race issue, as it occurs sometimes but not always. 

1. What specific action are you taking on Portainer? Are you updating a container? 
3. And I know you said this earlier, but what is the broken behavior? 
4. Is it that the IDs and names are incorrect? Or something else.

**Comment by FrancYescO** [comment] 2024-11-20 19:26
1) CI push an image > call portainer stack webhook > portainer pull and redeploy the stack (the updated pushed image)
2) container is shown on the sidebar but not loading logs as it points to a wrong container ID
3) ID (the one showed also in browser URL)

**Comment by amir20** [comment] 2024-11-20 20:49
I see. So wrong id, correct name. I didn't realize this is part of a stack. I can try it out.

**Comment by amir20** [comment] 2024-11-21 03:48
@FrancYescO, is dozzle part of your stack, or is it always running separately, and the stack is updated independently?

**Comment by FrancYescO** [comment] 2024-11-21 07:07
> @FrancYescO, is dozzle part of your stack, or is it always running separately, and the stack is updated independently? 

I have various stack, and dozzle is part of another stack

**Comment by amir20** [comment] 2024-11-21 16:23
@FrancYescO, no luck. I set up Portainer Community Edition and created a new stack like this:

```
services:
  echo:
    image: amir20/echo:latest
    command: -r
    deploy:
      replicas: 3 # Specifies three replicas
      update_config:
        parallelism: 1 # Update one container at a time
        delay: 10s # Wait 10s between updating each container
      restart_policy:
        condition: on-failure
        max_attempts: 3
```

Everything was working well in Dozzle. I redeployed the stack by changing `amir20/echo:latest` to `amir20/echo:v2`. I checked the logs, and everything looked fine. In Dozzle, all the IDs matched those in `docker ps`, and everything functioned properly.

I wonder if the issue is related to the webhooks. Unfortunately, that's beyond the time I have available. I can't seem to reproduce it easily. If you find a reliable way to reproduce it without setting up the entire pipeline, that would be helpful.

**Comment by FrancYescO** [comment] 2024-11-21 17:17
in my case the image, have ever the same "latest" tag.... but i don't think that matter... this happened 2 time more today (while the stack was probably redeployed with no dozzle issue 20+ more), but i was still not tracing the events properly i'll update here if i find something more

**Comment by FrancYescO** [comment] 2024-11-21 17:49
Ah what surely I should say is that during the portainer redeploy you will NEVER be redirected to the new container (but this can be a different issue related to https://github.com/amir20/dozzle/issues/3036 )

**Comment by amir20** [comment] 2024-11-22 15:58
Can you attach the whole logs? I am looking for other errors such as "docker store unexpectedly disconnected from docker events". It doesn't make sense why there is a bunch of "received container event" events and then suddenly they stop.

**Comment by FrancYescO** [comment] 2024-11-22 16:06
[dozzle-2024-11-22T14-39-12_.log.zip](https://github.com/user-attachments/files/17872939/dozzle-2024-11-22T14-39-12_.log.zip)

**Comment by amir20** [comment] 2024-11-22 16:13
OK it's not what I thought. But I have a wild guess. Give me a little time. Let me check something and provide a PR.

**Comment by amir20** [comment] 2024-11-22 16:24
https://github.com/amir20/dozzle/pull/3417 I am just taking a guess here. I noticed that after `e4c57f33f6d8` started, no other events were received. So I thought maybe it's blocking for some reason. 

I don't know why it would be but this would be a fix. Can you try `pr-3417`?

**Comment by FrancYescO** [comment] 2024-11-22 16:39
ok i'll leave this pr running, i'll update if happens again...

**Comment by amir20** [comment] 2024-11-22 16:41
If it works, it will make me go crazy why. Because currently, it shouldn't block.  

By the way, how many people are using Dozzle in a browser? Is it just you or is it a few?

**Comment by FrancYescO** [comment] 2024-11-22 16:54
few, but often non-concurrent

**Comment by amir20** [comment] 2024-11-22 17:28
Hmm, okay. That could explain what I am seeing. I'll add more debugging logs later. If my intuition is correct, a deadlock occurs after a new container is found because multiple sessions are trying to write to a channel.

**Comment by amir20** [comment] 2024-11-22 23:45
I am guessing that didn't solve your problem. I didn't realize you had originally `grep`ed the logs so only logs with `e4c57f33f6d8` were being displayed. Looking at the full log, it looks to be fine. 

It's crazy that I don't see `c8cabeb803ed` at all in the logs except for stats. I am pretty stumped right now.

**Comment by amir20** [comment] 2024-11-23 00:25
Alright, I think we need to do some deeper investigation. I have enabled stack trace dump in https://github.com/amir20/dozzle/pull/3418. You can deploy with `pr-3418`.

Next time this happens, go to `https://<path-to-dozzle>/debug`. You should see a page with link to `goroutine`s. Send me that page. I want to understand why container store is not receiving any events. This will tell me if that thread is stuck some where.  For a good state, we should see something like `/dozzle/internal/docker/container_store.go:176`. 

Let me know!

**Comment by amir20** [comment] 2024-11-25 16:08
I am going to merge the debug API to master. I felt adding an extra 500KB is not worth it. But whatever. If it was merged before then we could have troubleshooted this issue sooner. 

So you can try `master` if you want.

**Comment by FrancYescO** [comment] 2024-11-25 18:53
goroutine page

```

goroutine profile: total 98
29 @ 0x473ece 0x44fbc5 0x730ce7 0x47bea1
#	0x730ce6	net/http.(*persistConn).writeLoop+0xe6	/usr/local/go/src/net/http/transport.go:2519

28 @ 0x473ece 0x44fbc5 0x72fe05 0x47bea1
#	0x72fe04	net/http.(*persistConn).readLoop+0xca4	/usr/local/go/src/net/http/transport.go:2325

26 @ 0x473ece 0x4363d7 0x4731c5 0x4da407 0x4db6fa 0x4db6e8 0x503a45 0x5145c5 0x72e7aa 0x68ff03 0x690a09 0x6c0c9c 0x6c06a5 0x6c0a11 0x722edb 0x722db2 0x7328df 0x9a32ad 0x756568 0x756165 0x755e35 0xa43266 0xa4aaf0 0x47bea1
#	0x4731c4	internal/poll.runtime_pollWait+0x84							/usr/local/go/src/runtime/netpoll.go:351
#	0x4da406	internal/poll.(*pollDesc).wait+0x26							/usr/local/go/src/internal/poll/fd_poll_runtime.go:84
#	0x4db6f9	internal/poll.(*pollDesc).waitRead+0x279						/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
#	0x4db6e7	internal/poll.(*FD).Read+0x267								/usr/local/go/src/internal/poll/fd_unix.go:165
#	0x503a44	net.(*netFD).Read+0x24									/usr/local/go/src/net/fd_posix.go:55
#	0x5145c4	net.(*conn).Read+0x44									/usr/local/go/src/net/net.go:189
#	0x72e7a9	net/http.(*persistConn).Read+0x49							/usr/local/go/src/net/http/transport.go:2052
#	0x68ff02	bufio.(*Reader).fill+0x102								/usr/local/go/src/bufio/bufio.go:110
#	0x690a08	bufio.(*Reader).ReadSlice+0x28								/usr/local/go/src/bufio/bufio.go:376
#	0x6c0c9b	net/http/internal.readChunkLine+0x1b							/usr/local/go/src/net/http/internal/chunked.go:156
#	0x6c06a4	net/http/internal.(*chunkedReader).beginChunk+0x24					/usr/local/go/src/net/http/internal/chunked.go:49
#	0x6c0a10	net/http/internal.(*chunkedReader).Read+0x130						/usr/local/go/src/net/http/internal/chunked.go:125
#	0x722eda	net/http.(*body).readLocked+0x3a							/usr/local/go/src/net/http/transfer.go:844
#	0x722db1	net/http.(*body).Read+0x111								/usr/local/go/src/net/http/transfer.go:836
#	0x7328de	net/http.(*bodyEOFSignal).Read+0x13e							/usr/local/go/src/net/http/transport.go:2913
#	0x9a32ac	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*wrappedBody).Read+0x2c	/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.53.0/transport.go:241
#	0x756567	encoding/json.(*Decoder).refill+0x187							/usr/local/go/src/encoding/json/stream.go:165
#	0x756164	encoding/json.(*Decoder).readValue+0x84							/usr/local/go/src/encoding/json/stream.go:140
#	0x755e34	encoding/json.(*Decoder).Decode+0x74							/usr/local/go/src/encoding/json/stream.go:63
#	0xa43265	github.com/amir20/dozzle/internal/docker.(*httpClient).ContainerStats+0x165		/dozzle/internal/docker/client.go:239
#	0xa4aaef	github.com/amir20/dozzle/internal/docker.streamStats+0x18f				/dozzle/internal/docker/stats_collector.go:78

2 @ 0x473ece 0x4363d7 0x4731c5 0x4da407 0x4db6fa 0x4db6e8 0x503a45 0x5145c5 0x72e7aa 0x68ff03 0x690a09 0x6c0c9c 0x6c06a5 0x6c0a11 0x722edb 0x722db2 0x7328df 0x9a32ad 0x756568 0x756165 0x755e35 0x9bbfc5 0x47bea1
#	0x4731c4	internal/poll.runtime_pollWait+0x84							/usr/local/go/src/runtime/netpoll.go:351
#	0x4da406	internal/poll.(*pollDesc).wait+0x26							/usr/local/go/src/internal/poll/fd_poll_runtime.go:84
#	0x4db6f9	internal/poll.(*pollDesc).waitRead+0x279						/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
#	0x4db6e7	internal/poll.(*FD).Read+0x267								/usr/local/go/src/internal/poll/fd_unix.go:165
#	0x503a44	net.(*netFD).Read+0x24									/usr/local/go/src/net/fd_posix.go:55
#	0x5145c4	net.(*conn).Read+0x44									/usr/local/go/src/net/net.go:189
#	0x72e7a9	net/http.(*persistConn).Read+0x49							/usr/local/go/src/net/http/transport.go:2052
#	0x68ff02	bufio.(*Reader).fill+0x102								/usr/local/go/src/bufio/bufio.go:110
#	0x690a08	bufio.(*Reader).ReadSlice+0x28								/usr/local/go/src/bufio/bufio.go:376
#	0x6c0c9b	net/http/internal.readChunkLine+0x1b							/usr/local/go/src/net/http/internal/chunked.go:156
#	0x6c06a4	net/http/internal.(*chunkedReader).beginChunk+0x24					/usr/local/go/src/net/http/internal/chunked.go:49
#	0x6c0a10	net/http/internal.(*chunkedReader).Read+0x130						/usr/local/go/src/net/http/internal/chunked.go:125
#	0x722eda	net/http.(*body).readLocked+0x3a							/usr/local/go/src/net/http/transfer.go:844
#	0x722db1	net/http.(*body).Read+0x111								/usr/local/go/src/net/http/transfer.go:836
#	0x7328de	net/http.(*bodyEOFSignal).Read+0x13e							/usr/local/go/src/net/http/transport.go:2913
#	0x9a32ac	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*wrappedBody).Read+0x2c	/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.53.0/transport.go:241
#	0x756567	encoding/json.(*Decoder).refill+0x187							/usr/local/go/src/encoding/json/stream.go:165
#	0x756164	encoding/json.(*Decoder).readValue+0x84							/usr/local/go/src/encoding/json/stream.go:140
#	0x755e34	encoding/json.(*Decoder).Decode+0x74							/usr/local/go/src/encoding/json/stream.go:63
#	0x9bbfc4	github.com/docker/docker/client.(*Client).Events.func1+0x404				/go/pkg/mod/github.com/docker/docker@v27.3.1+incompatible/client/events.go:51

1 @ 0x40f709 0x475c89 0x744f33 0x47bea1
#	0x475c88	os/signal.signal_recv+0x28	/usr/local/go/src/runtime/sigqueue.go:152
#	0x744f32	os/signal.loop+0x12		/usr/local/go/src/os/signal/signal_unix.go:23

1 @ 0x432ed1 0x472dfd 0xc24d71 0xc24ba5 0xc219cb 0xc3bc4f 0xaeed62 0x716409 0xc3eced 0x716409 0xaec96f 0xaee2fb 0x716409 0xaeed62 0x716409 0xc43a90 0x716409 0xaec92e 0x73588e 0x714db0 0x47bea1
#	0xc24d70	runtime/pprof.writeRuntimeProfile+0xb0				/usr/local/go/src/runtime/pprof/pprof.go:793
#	0xc24ba4	runtime/pprof.writeGoroutine+0x44				/usr/local/go/src/runtime/pprof/pprof.go:752
#	0xc219ca	runtime/pprof.(*Profile).WriteTo+0x14a				/usr/local/go/src/runtime/pprof/pprof.go:374
#	0xc3bc4e	net/http/pprof.handler.ServeHTTP+0x52e				/usr/local/go/src/net/http/pprof/pprof.go:272
#	0xaeed61	github.com/go-chi/chi/v5.(*Mux).routeHTTP+0x2e1			/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459
#	0x716408	net/http.HandlerFunc.ServeHTTP+0x28				/usr/local/go/src/net/http/server.go:2220
#	0xc3ecec	github.com/go-chi/chi/v5/middleware.NoCache.func1+0x28c		/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/nocache.go:55
#	0x716408	net/http.HandlerFunc.ServeHTTP+0x28				/usr/local/go/src/net/http/server.go:2220
#	0xaec96e	github.com/go-chi/chi/v5.(*Mux).ServeHTTP+0x32e			/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:73
#	0xaee2fa	github.com/go-chi/chi/v5.(*Mux).Mount.func1+0x1ba		/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:327
#	0x716408	net/http.HandlerFunc.ServeHTTP+0x28				/usr/local/go/src/net/http/server.go:2220
#	0xaeed61	github.com/go-chi/chi/v5.(*Mux).routeHTTP+0x2e1			/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459
#	0x716408	net/http.HandlerFunc.ServeHTTP+0x28				/usr/local/go/src/net/http/server.go:2220
#	0xc43a8f	github.com/amir20/dozzle/internal/web.cspHeaders.func1+0xef	/dozzle/internal/web/csp.go:13
#	0x716408	net/http.HandlerFunc.ServeHTTP+0x28				/usr/local/go/src/net/http/server.go:2220
#	0xaec92d	github.com/go-chi/chi/v5.(*Mux).ServeHTTP+0x2ed			/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90
#	0x73588d	net/http.serverHandler.ServeHTTP+0x8d				/usr/local/go/src/net/http/server.go:3210
#	0x714daf	net/http.(*conn).serve+0x5cf					/usr/local/go/src/net/http/server.go:2092

1 @ 0x473ece 0x409af9 0x409932 0xa4a396 0x47bea1
#	0xa4a395	github.com/amir20/dozzle/internal/docker.(*StatsCollector).Subscribe.func1+0x35	/dozzle/internal/docker/stats_collector.go:40

1 @ 0x473ece 0x409d7c 0x409932 0xc50437 0x43d98b 0x47bea1
#	0xc50436	main.main+0x1996	/dozzle/main.go:214
#	0x43d98a	runtime.main+0x28a	/usr/local/go/src/runtime/proc.go:272

1 @ 0x473ece 0x409d7c 0x409952 0xa4b5f6 0x47bea1
#	0xa4b5f5	github.com/amir20/dozzle/internal/docker.(*StatsCollector).Start.func2+0x75	/dozzle/internal/docker/stats_collector.go:124

1 @ 0x473ece 0x4363d7 0x4731c5 0x4da407 0x4db6fa 0x4db6e8 0x503a45 0x5145c5 0x72e7aa 0x68ff03 0x690033 0x72f2e5 0x47bea1
#	0x4731c4	internal/poll.runtime_pollWait+0x84		/usr/local/go/src/runtime/netpoll.go:351
#	0x4da406	internal/poll.(*pollDesc).wait+0x26		/usr/local/go/src/internal/poll/fd_poll_runtime.go:84
#	0x4db6f9	internal/poll.(*pollDesc).waitRead+0x279	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
#	0x4db6e7	internal/poll.(*FD).Read+0x267			/usr/local/go/src/internal/poll/fd_unix.go:165
#	0x503a44	net.(*netFD).Read+0x24				/usr/local/go/src/net/fd_posix.go:55
#	0x5145c4	net.(*conn).Read+0x44				/usr/local/go/src/net/net.go:189
#	0x72e7a9	net/http.(*persistConn).Read+0x49		/usr/local/go/src/net/http/transport.go:2052
#	0x68ff02	bufio.(*Reader).fill+0x102			/usr/local/go/src/bufio/bufio.go:110
#	0x690032	bufio.(*Reader).Peek+0x52			/usr/local/go/src/bufio/bufio.go:148
#	0x72f2e4	net/http.(*persistConn).readLoop+0x184		/usr/local/go/src/net/http/transport.go:2205

1 @ 0x473ece 0x4363d7 0x4731c5 0x4da407 0x4df7d5 0x4df7c3 0x505a09 0x51dade 0x51ccb0 0x719e2c 0x719af1 0xc50a35 0x47bea1
#	0x4731c4	internal/poll.runtime_pollWait+0x84		/usr/local/go/src/runtime/netpoll.go:351
#	0x4da406	internal/poll.(*pollDesc).wait+0x26		/usr/local/go/src/internal/poll/fd_poll_runtime.go:84
#	0x4df7d4	internal/poll.(*pollDesc).waitRead+0x294	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
#	0x4df7c2	internal/poll.(*FD).Accept+0x282		/usr/local/go/src/internal/poll/fd_unix.go:620
#	0x505a08	net.(*netFD).accept+0x28			/usr/local/go/src/net/fd_unix.go:172
#	0x51dadd	net.(*TCPListener).accept+0x1d			/usr/local/go/src/net/tcpsock_posix.go:159
#	0x51ccaf	net.(*TCPListener).Accept+0x2f			/usr/local/go/src/net/tcpsock.go:372
#	0x719e2b	net/http.(*Server).Serve+0x30b			/usr/local/go/src/net/http/server.go:3330
#	0x719af0	net/http.(*Server).ListenAndServe+0x70		/usr/local/go/src/net/http/server.go:3259
#	0xc50a34	main.main.func3+0x94				/dozzle/main.go:207

1 @ 0x473ece 0x44fbc5 0x744ac6 0x47bea1
#	0x744ac5	os/signal.NotifyContext.func1+0x65	/usr/local/go/src/os/signal/signal.go:288

1 @ 0x473ece 0x44fbc5 0xa43c77 0xa45b18 0x47bea1
#	0xa43c76	github.com/amir20/dozzle/internal/docker.(*httpClient).ContainerEvents+0x136		/dozzle/internal/docker/client.go:303
#	0xa45b17	github.com/amir20/dozzle/internal/docker.(*ContainerStore).checkConnectivity.func1+0xf7	/dozzle/internal/docker/container_store.go:56

1 @ 0x473ece 0x44fbc5 0xa43c77 0xa4b8e2 0x47bea1
#	0xa43c76	github.com/amir20/dozzle/internal/docker.(*httpClient).ContainerEvents+0x136	/dozzle/internal/docker/client.go:303
#	0xa4b8e1	github.com/amir20/dozzle/internal/docker.(*StatsCollector).Start.func1+0x101	/dozzle/internal/docker/stats_collector.go:116

1 @ 0x473ece 0x44fbc5 0xa4650d 0x47bea1
#	0xa4650c	github.com/amir20/dozzle/internal/docker.(*ContainerStore).init+0x16c	/dozzle/internal/docker/container_store.go:176

1 @ 0x473ece 0x44fbc5 0xa4b21e 0xa461a8 0x47bea1
#	0xa4b21d	github.com/amir20/dozzle/internal/docker.(*StatsCollector).Start+0x49d			/dozzle/internal/docker/stats_collector.go:138
#	0xa461a7	github.com/amir20/dozzle/internal/docker.(*ContainerStore).SubscribeEvents.func1+0x27	/dozzle/internal/docker/container_store.go:139

1 @ 0x47bea1
```

**Comment by FrancYescO** [comment] 2024-11-25 19:09
I've deleted my comments, was nothing related to this issue...still waiting for this to rehappen.

**Comment by amir20** [comment] 2024-11-26 16:44
So has this not happened yet?

**Comment by FrancYescO** [comment] 2024-11-26 17:29
Now that i'm waiting for it, no 😅

Unfortunately the stack update now are fewer per day so less possibilities to retrigger...and I was just wondering if this can happen only if there are concurrent users using dozzle on the same container

**Comment by amir20** [comment] 2024-12-03 15:41
Any update?

**Comment by FrancYescO** [comment] 2024-12-04 07:10
Unfortunately not.

I'm start thinking the bug was caused only if multiple user are on the same container log that is being redeployed, but i'm still on the pr where you just added debug and the issue still not popupped again...

**Comment by amir20** [comment] 2024-12-04 20:21
Even if multiple users were present, I would imagine it would be the same thing as having multiple tabs open for one user. Which is something I do often. 

I am going to close this. You can update to the latest release. As long as debug is enabled, you should be able to get me stracktrace. 

I'll close this. Let's open a new one if it is found.

**Closed by amir20** 2024-12-04 20:21 UTC
Labels: bug
