### ISSUE TITLE
PWA favicon missing 

### ISSUE THREAD

**Issue by agneevX** [amir20/dozzle#2400] opened 2023-09-30 07:22 UTC
**Describe the bug**

Currently, Dozzle lacks a favicon and/or `apple-touch-icon`, which makes it difficult to add the PWA to the dock or home screens on iOS or Android.

**To Reproduce**

1. Add site to Home Screen/Dock on iOS/macOS

**Expected behavior**

Favicon should appear automatically.

**Screenshots**

![Screenshot](https://github.com/amir20/dozzle/assets/19761269/6f61576b-4289-40f3-808c-aae88645f938)

**Desktop (please complete the following information):**

- OS: macOS
- Docker version: N/A
- Browser & version: Safari 17.0
- Version: 5.0.3

**If applicable include logs with `--level debug` and browser logs**

**Comment by amir20** [comment] 2023-09-30 14:15
Are you in my head? Lol I was just thinking about this. Maybe because of the new MacOS every one is also trying it. 

I do have favicon but Safari doesn't support SVG. So I'll have to figure out how to make PNGs. Will fix it when I find a decent a solution that doesn't increase the size.

**Comment by agneevX** [comment] 2023-09-30 15:34
Haha! Good thing macOS lets you add a custom icon, so I added one from a google search. Not sure if it's an official icon though.

![Screenshot](https://github.com/amir20/dozzle/assets/19761269/e236d50e-9827-458c-8aa8-12a13d98491e)

**Comment by amir20** [comment] 2023-09-30 16:21
Yea, but I fI do it right, you don't have to do that. 

Now, I remember why I didn't do this a while back. Dozzle can be mounted on different folders like `/` or `/foobar` and I couldn't figure out how to generate PWA manifest to handle the sub folders. Maybe I'll find a better solution.

**Comment by amir20** [comment] 2023-09-30 20:31
#2402 should fix this. Test with `amir20/dozzle:pr-2402`. I only added the icon which I think should be enough. I didn't register PWA manifest because I don't think it's really needed.

**Comment by agneevX** [comment] 2023-10-01 13:42
That looks good!

**Comment by amir20** [comment] 2023-10-01 22:02
Great. I'll close this. I was able to test locally but for some reason my https doesn't work. But that might be due to my proxy and unrelated to Dozzle. For now, I can confirm the file is there.

**Closed by amir20** 2023-10-01 22:02 UTC
