### ISSUE TITLE
Forward Proxy: Unable to find remote user

### ISSUE THREAD

**Issue by Aetherinox** [amir20/dozzle#3119] opened 2024-07-16 17:57 UTC
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

8.0.5

### 🐛 Describe the bug / provide steps to reproduce it

Enabling Forward-Proxy results in the following error:

```
level=errormsg=Unable to find remote user. Please check your proxy configuration. Expecting headers 
Remote-Email, Remote-User, Remote-Name.
```

<br />

Have set the headers for Authentik:

```
    environment:
      DOZZLE_AUTH_PROVIDER: forward-proxy
      DOZZLE_AUTH_HEADER_USER: X-authentik-username
      DOZZLE_AUTH_HEADER_EMAIL: X-authentik-email
      DOZZLE_AUTH_HEADER_NAME: X-authentik-name
```

The odd thing is that when I go Dozzle, it does re-direct me to Authentik and allow me to sign in, and then goes to Dozzle's dashboard. Don't seem to have an issue with that. And if I kill my authentik cookies, it'll redirect me back to sign in for Dozzle through Authentik as it normally should.

I went to Authentik's docs just to double confirm the header values, and they seem correct.

### 💻 Environment

```
Client: Docker Engine - Community
 Version:    27.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 29
  Running: 26
  Paused: 0
  Stopped: 3
 Images: 49
 Server Version: 27.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-41-generic
 Operating System: Ubuntu 23.10
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.61GiB
 Name: x.internal.dev
 ID: 2fa042bc-e2d8-13fa-ef1a-5c726a423537
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### 📜 If applicable, attach your Dozzle logs. You many need to enable debug mode. See https://dozzle.dev/guide/debugging.

```
level=infomsg=Dozzle version v8.0.5
level=debugmsg=filterArgs = {map[]}
level=debugmsg=Creating a client with host: ID: 2fa042bc-e2d8-13fa-ef1a-5c726a423537, Endpoint: local
level=debugmsg=connected to local Docker Engine
level=infomsg=Connected to 1 Docker Engine(s)
level=debugmsg=subscribing to docker events from container store ID: 2fa042bc-e2d8-13fa-ef1a-5c726a423537, Endpoint: local
level=infomsg=Accepting connections on :8080
level=debugmsg=finding container with id: 546f1bb11c26
level=debugmsg=finding container with id: 1ab4def5eb59
level=debugmsg=finding container with id: 554fec0f9251
level=debugmsg=finding container with id: af5bf8d3f471
level=errormsg=Unable to find remote user. Please check your proxy configuration. Expecting headers Remote-Email, Remote-User, Remote-Name.
level=debugmsg=Cache miss for []releases.Release
```

**Comment by amir20** [comment] 2024-07-16 19:31
You missed an important debug that should spit out all the headers at the end. You should see `Dumping all headers for url`. 

Do you see `X-authentik-username` in those logs?  

> Unable to find remote user. Please check your proxy configuration. Expecting headers Remote-Email, Remote-User, Remote-Name

That log is hard coded so you'll have to see the headers to further understand what is happening. I won't have time to setup authentik though.

**Comment by Aetherinox** [comment] 2024-07-17 05:45
I just checked the logs again, there's definitely no `Dumping all headers for url` in the logs. I checked using Dozzle, Portainer, and then also manually checked the log files.

Also did a fresh restart on Dozzle, still doesn't show that particular error.

Went through the logs again and no, I don't see `X-authentik-username` being mentioned. I figured the error message was hard-coded though, because from all examples I can find, the headers have been properly declared as an env var.

Is their another specific setting that must be enabled to get the `Dumping all headers` error? I'll go back and mess with it more, but 100% don't see that message printed anywhere in the logs. Both before and after some restarts.

**Comment by amir20** [comment] 2024-07-18 00:15
> The odd thing is that when I go Dozzle, it does re-direct me to Authentik and allow me to sign in, and then goes to Dozzle's dashboard. Don't seem to have an issue with that. And if I kill my authentik cookies, it'll redirect me back to sign in for Dozzle through Authentik as it normally should.

I think I misunderstood something. So it is redirecting you and you do see Dozzle's dashboard after signin. Is that right? 

Are you just asking why there is a log `level=errormsg=Unable to find remote user. Please check your proxy configuration. Expecting headers Remote-Email, Remote-User, Remote-Name` ?

Sorry, if I am not understanding something here.  From the logs, I don't see anything broken since the logs are being loaded.

**Comment by amir20** [comment] 2024-07-18 00:19
Although it is weird that the only code that throws that exception is at https://github.com/amir20/dozzle/blob/01afadd410bcb5e0e8e866e622a4afd14e31e009/internal/web/index.go#L72 which would mean it should dump out all the logs. 

Something not making sense here 😂

**Comment by Aetherinox** [comment] 2024-07-18 02:47
Oh, sorry. Yes, I am just reporting the error, because it doesn't make sense that it's throwing that error, yet from what I can see, it "appears" that Authentik is working fine. I can sign in with Authentik, use Dozzle, etc.

Was just wondering if this has some unknown side effect I'm just not seeing yet.

But now I'm also wondering why my logs look so simple, but other users are getting headers being bumped, and can see much more at startup.

**Comment by Aetherinox** [comment] 2024-07-18 03:18
Nope. I just made a bunch of edits to my docker-compose. I hard-coded all the needed env vars
```
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_AUTH_PROVIDER=forward-proxy
      - DOZZLE_AUTH_HEADER_USER=X-authentik-username
      - DOZZLE_AUTH_HEADER_EMAIL=X-authentik-email
      - DOZZLE_AUTH_HEADER_NAME=X-authentik-name
      - DOZZLE_LEVEL=debug
```

I tried completely removing the healthcheck just for extra testing, all I'm doing is making my logs shorter and shorter.

**Comment by amir20** [comment] 2024-07-18 15:58
I wasn't able to reproduce this. I tested with `nginx` using:

```conf
events {}
http {
    server {
        listen 9009;

        location / {
            proxy_pass http://localhost:8080;
            proxy_set_header X-authentik-username amir;
            proxy_set_header X-authentik-email amir@example.com;
            proxy_set_header X-authentik-name "Amir Raminfar";
        }
    }
}
```

With compose:

```yml
services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      DOZZLE_AUTH_PROVIDER: forward-proxy
      DOZZLE_AUTH_HEADER_USER: X-authentik-username
      DOZZLE_AUTH_HEADER_EMAIL: X-authentik-email
      DOZZLE_AUTH_HEADER_NAME: X-authentik-name
      DOZZLE_LEVEL: debug
```

I see the logs with no error: 

```
dozzle-1  | time="2024-07-18T15:55:05Z" level=debug msg="Fetching avatar from https://gravatar.com/avatar/6111b1e9fad82ba4a9e3d3e80a644126?d=https%3A%2F%2Fui-avatars.com%2Fapi%2F/Amir+Raminfar/128"
dozzle-1  | time="2024-07-18T15:55:05Z" level=debug msg="resetting timer for container stats collector ID: ivkagb8ir869qgj2ft73t2fbg, Endpoint: local"
dozzle-1  | time="2024-07-18T15:55:05Z" level=debug msg="starting to stream stats for: a395f7e38baa"
dozzle-1  | time="2024-07-18T15:55:05Z" level=debug msg="subscribing to docker events from stats collector ID: ivkagb8ir869qgj2ft73t2fbg, Endpoint: local"
dozzle-1  | time="2024-07-18T15:55:05Z" level=debug msg="starting to stream stats for: f0a366ce21ec"
dozzle-1  | time="2024-07-18T15:55:05Z" level=debug msg="starting to stream stats for: e0776249d72f"
dozzle-1  | time="2024-07-18T15:55:05Z" level=debug msg="Cache miss for []releases.Release"

```

Then if I hit Dozzle directly: 

```
dozzle-1  | time="2024-07-18T15:57:04Z" level=error msg="Unable to find remote user. Please check your proxy configuration. Expecting headers Remote-Email, Remote-User, Remote-Name."
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Dumping all headers for url /"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="User-Agent: [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Accept: [text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Sec-Fetch-Site: [none]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Accept-Encoding: [gzip, deflate, br, zstd]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Sec-Ch-Ua-Mobile: [?0]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Connection: [keep-alive]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Dnt: [1]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Upgrade-Insecure-Requests: [1]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Sec-Fetch-User: [?1]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Sec-Fetch-Dest: [document]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Sec-Ch-Ua: [\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\"]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Sec-Ch-Ua-Platform: [\"macOS\"]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Sec-Fetch-Mode: [navigate]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Accept-Language: [en-US,en;q=0.9]"
dozzle-1  | time="2024-07-18T15:57:04Z" level=debug msg="Cookie: [_ga=GA1.1.1053226785.1715118569; _ga_X3Z4496XFK=GS1.1.1715181566.2.1.1715181828.0.0.0]"
```

So maybe you help reproduce it without setting up Authentik because that's a little too much for me to do.

**Comment by Aetherinox** [comment] 2024-07-18 17:41
Alright, I'll throw up Nginx.

What specific action triggers the `Dumping all headers for url` message?

According to the code, all you're doing is just checking for `FORWARX_PROXY`

```go
} else if h.config.Authorization.Provider == FORWARD_PROXY {
```

So I should be able to simply set my proxy type to `forward-proxy` and I should be setting those messages? Or is it also combined with a bad header name that doesn't exist?:

```yml
DOZZLE_AUTH_HEADER_USER: something-that-doesnt-exist
```

**Comment by amir20** [comment] 2024-07-20 21:55
@Aetherinox 

> What specific action triggers the Dumping all headers for url message?

Loading the homepage will load index.go file which should print the headers. 

> So I should be able to simply set my proxy type to forward-proxy and I should be setting those messages? Or is it also combined with a bad header name that doesn't exist?:

It just prints all headers. 

If you can just use something I can reproduce then it would be easier. I am not sure what is happening and why `dumping all headers` is not work for you.

**Comment by amir20** [comment] 2024-07-20 21:55
Let me know if we should close this because I don't think there is a bug here.

**Comment by amir20** [comment] 2024-07-23 02:59
Not sure what to do with this issue and nothing seems to be broken. So closing.

**Closed** 2024-07-23 02:59 UTC
Labels: bug
