### ISSUE TITLE
One container renamed to 'cottage' and the same string is added on top of all shown logs inside Dozzle.

### ISSUE THREAD

**Issue by f-steff** [amir20/dozzle#2153] opened 2023-04-26 14:07 UTC
**Describe the bug**

I'm not sure this is a Dozzle bug, but since I can only find the error in the Dozzle GUI I guess it's likely.

A container is renamed 'cottage' in the list of containers, and the same name is added to the header of all logs.
I've tested with 4.10.0 and the latest and got the same strange behavior in both cases.
The problem suddenly appeared after a reboot using dozzle 4.10.0, which I have been running for the last few days.

For testing purposes, I have a number of containers running on Docker for Windows:
   dozzle, gitea, gitea_db, mermaid_live_editor, traefik, whoami, and yacht.
They are listed with those names in Docker for Windows and using 'docker ps'.
However, in Dozzle GUI, the container list is:
   dozzle, cottage, gitea_db, mermaid_live_editor, traefik, whoami, and yacht.

If I click on the dozzle container to view the log, the top of the log, where the container name is located, is prepended by the string 'cottage' in slightly bigger letters than the rest of the line. 
For dozzle, the string is: cottage amir20/dozzle:v4.10.0
For cottage aka gitea, the string is cottage gitea:gitea:1.18.1
etc.

I have not been able to find the string cottage anywhere on my system.
It should be noted that all my containers are started using individual docker-compose.yml files and that all containers are named.

**To Reproduce**
I haven't been able to reproduce this behavior on my other Windows PC. 
On the other hand, I can't remove this behavior on this PC, despite reboots and restarts of containers.

**Desktop (please complete the following information):**
- OS: [e.g. iOS, Windows or Mac Os]  
Windows 11.
- Docker version [e.g. `docker version`'s output]
Docker Desktop 4.18.0 (104112)
- Browser & version [e.g. chrome, safari]
Tested on Chrome, Edge and Safari

**Comment by amir20** [comment] 2023-04-26 19:23
Oops wrong commit

**Comment by amir20** [comment] 2023-04-26 19:39
@f-steff so this would be funny if it does turn out to be a bug. 

Dozzle's UI is very thin and not much data manipulation is done. Dozzle's API just fetches data from Docker and converts to JSON. So I can't imagine how this could happen. 

Nonetheless, we should probably figure out what is happening. 

1. Can you provide a screenshot so I see exactly what is going on? 
2. Show `docker ps` and let's make sure we match docker id
3. Open network tab and look for `https://HOST/api/events/stream?host=localhost`.  First event should be `containers-changed` where all the containers are listed. Do you see `cottage` there? 
4. Finally, if you can, right click on the word cottage and choose `inspect`. Can you take a screenshot of that? 


Possibly there might be browser extension that might be doing this. I can also add more logging in Dozzle for `debug` mode that could print the names before sending it to the browser. 


Hope this will figure out what is causing this weird bug.

**Comment by f-steff** [comment] 2023-04-26 21:08
Thank you for your quick response, @amir20 .

I agree it's a really strange issue, and I believe it's a browser issue.
I tried testing in Chrome incognito mode, where I have no extensions running, and it gave the same problem.
A few further things I did notice, though:

1A. On first (re)load of Dozzle, where only the list of containers are listed, all the containers are correctly named.
![1A_Initial_Open_Dozzle](https://user-images.githubusercontent.com/7275320/234696386-480e670b-9612-4d11-aaaf-3bc4d01422b8.png)

1B. The moment I select a container to show its log, the gitea container (Second in the list) shows up as Cottage.
![1B_Dozzle_Screenshot_with_cottage_string](https://user-images.githubusercontent.com/7275320/234696395-73a2b97a-67cd-46f2-937d-570009762e10.png)

2. The output of `docker ps`. As can be seen cottage is not listed. (But a few more containers on this PC)
![2_docker_ps](https://user-images.githubusercontent.com/7275320/234696392-4c0fb4ec-d527-4251-bca6-f9c4c3e58fa7.png)

3. I tried to find the events you mention in the network tab, but was not able to.
When reloading the dozzle page, only two URI looks similar to the pattern you mention:
   https://dozzle.internal.company.com/api/logs/stream?id=13cfff8e3ba2&lastEventId=&host=localhost
   https://dozzle.internal.company.com/api/events/stream?host=localhost
However, I could not find any events nor a list of containers. I did find a list of the lines in the log displayed, though.

4. Below are the `inspect` output for the two locations of "cottage" on the screen:
![4_Cottage_in_container_list](https://user-images.githubusercontent.com/7275320/234696397-cf0e6c1b-0db2-4364-b8b0-f104baa5d488.png)
![4_Cottage_in_log](https://user-images.githubusercontent.com/7275320/234696401-781720a6-5867-4a81-8933-a0d2108f6e8c.png)

5. I finally also captured the `inspect` output for the initial container list with "gitea" on the screen:
![5_Gitea_in_container_list](https://user-images.githubusercontent.com/7275320/234702376-b6e82fc4-65fa-4cdf-a9a5-f65a03025430.png)

I hope all of this makes more sense to you than to me, as I'm really puzzled by this issue.

**Comment by amir20** [comment] 2023-04-26 23:26
Looking at the HTML, it makes no sense! It looks like some text was replaced every where. Even title is `title="cottage"`

Ok can you go to `https://dozzle.internal.company.com/api/events/stream?host=localhost`? Just open the browser. It should just be a bunch of JSON. I want to make sure the first line doesn't have any `cottage` in it. 

I need to think about this a little more. It's a weird bug for sure. Next step is to have some debug statements.

**Comment by f-steff** [comment] 2023-04-27 08:22
Searching through the JSON I find no mention of `cottage`.

I then switched back to the regular Dozzle screen and confirmed `gitea` had not been replaced on the container list screen, as usual, and when selecting to see the log of Dozzle, the `gitea` container name was replaced with `cottage` also as usual (for this issue), but to my big surprise the top of the container log was not changed to `cottage` as usual, instead it was changed to `gitea_db` as you can see in the screen-snap below.

![cottage_and_static_gitea_db](https://user-images.githubusercontent.com/7275320/234801657-d556c6ad-a29a-45f1-ad8f-4f1972eec8a8.png)

Switching through the logs of various containers the `gitea_db` name remained next to the image string of all the logs.

All this lasted till I reloaded the Dozzle browser tab, then the `cottage` string was shown again.

All of the above happened in a regular Chrome tab.

Looking at this from an embedded programmer perspective, I would suspect some sort of loose pointer.

**Comment by amir20** [comment] 2023-04-27 15:28
This is totally bonkers. It's time to add some debugging because something is unique to your env.  I get about 20k sessions/day and no one else has reported it. 

Let me add some debugging statements and have you test that. I honestly don't know what to look but hoping it would give us an idea. 

Another question: How easy would it be for you to give me access to your environment so I can debug personally? I understand if you can't.

**Comment by f-steff** [comment] 2023-04-27 15:55
Unfortunately it's not possible for me to give you access to our company network or to a computer. Company policy even block Teams screen-sharing to outside parties. :-(

The tests I've been doing indicate that this issue is only occurring on one PC. I have an almost identical PC without the issue. 
On both PC's I have the same containers running, started using the exact same Docker-compose.yml, both routing containers through traefik and both have the same URL's mapped to local host (for reverse proxying). 
Docker and browser versions are identical. 

As for debug statements, perhaps just start by printing container names in html comments, perhaps with a hyphen inserted so simple text substitution can be avoided such as this: <!- g-itea --> ?

**Comment by amir20** [comment] 2023-04-27 16:17
I figured you couldn't give access. 

I just pushed https://github.com/amir20/dozzle/pull/2158

You should be able to test it with `amir20/dozzle:pr-2158` tag. 

You need to go in your browser and enable verbose mode. 

<img width="1240" alt="Screenshot 2023-04-27 at 8 44 11 AM" src="https://user-images.githubusercontent.com/260667/234923409-065af7d4-5bab-4343-9c5d-97253008805f.png">

The two logs I added print the name when they are updated from the API and when showing logs. 

> Looking at this from an embedded programmer perspective, I would suspect some sort of loose pointer.

That's the weird part. I don't handle any logic when the containers are clicked. It's handled by the routing logic by passing the `id` and finding the containers that match the id. No mutations should be done. 

These logs should at least help to identify a data problem vs some rendering.

**Comment by f-steff** [comment] 2023-04-27 16:24
Thanks a lot!
I'm with my kids at a school performance right now. Will be able to test in about two hours from now.

**Comment by amir20** [comment] 2023-04-27 16:28
My kids aren't old enough to have school performance yet. 🥇   No rush. 

This will be the most interesting bug I have seen for a while.

**Comment by f-steff** [comment] 2023-04-28 11:29
Sorry for the long response time (had a blast with my kids (10 & 12) yesterday, and helped clean up afterward, which took much longer than anticipated.).

I've been testing the `amir20/dozzle:pr-2158` version, and have discovered a bit more about the issue.

If I load the `dozzle` tab without a container selected, I (still) see two container lists and each container has its proper name. In the verbose output, I see a number of `Creating container name: <name>, existing: false`, one for each container and each one having the correct container name. If I down a container no verbose output is given. If I up it again, the verbose output `Creating container name: <name>, existing: true` is given for all existing containers and `Creating container name: <name>, existing: false` for the particular container I cycled.

If I then select a container to be shown, I get the verbose output `Showing container name: <name>, id: <hex ID>` with the correct container name. To my surprise, the names in the container list remain unchanged (no `cottage`), and the container name (next to the image:tag) on top of the log is shown correctly. Even when switching from container to container, everything is working as it should.

However, if I have `dozzle` selected and press F5 to reload the page, then my gitea container is instantly renamed to `cottage` in the container list. Looking at the verbose output I get `Showing container name: undefined, id: <hex ID>`, where the ID matches the selected container, but the name is undefined. I then see a number of `Creating container name: <name>, existing: false`, one for each container and each one having the correct container name. Finally, I see `Showing container name: <name>, id: <hex ID>` with both name and ID matching the selected container. If I select the container names `cottage` in the container list, I still see the correct container name in the verbose output: `Showing container name: gitea, id: <hex ID>`.
After the F5-reload, if I take the gitea container down while it's log is shown, the log remains visible.
Bring it up again the container immediately shows up in the container list as cottage, also the shown log (including memory, etc. header) is cleared. In the verbose output I get a number of `Creating container name: <name>, existing: true`, one for each existing container and `Creating container name: gitea, existing: false`, for the cycled container.  
I then get the following list of errors, in which `Showing container name: undefined, id: <hex ID>` also shows up, where the ID is the ID of the previously selected container (which no longer exist).

`
index-aa2b6c04.js:1 TypeError: Cannot read properties of undefined (reading 'getLastStat')
    at index-aa2b6c04.js:46:38027
    at dn (index-aa2b6c04.js:1:14386)
    at sa.l [as fn] (index-aa2b6c04.js:1:19756)
    at sa.run (index-aa2b6c04.js:1:5605)
    at sa.v [as scheduler] (index-aa2b6c04.js:1:20122)
    at tl (index-aa2b6c04.js:1:6941)
    at ri (index-aa2b6c04.js:1:6877)
    at ua (index-aa2b6c04.js:1:12493)
    at sa.scheduler (index-aa2b6c04.js:1:13977)
    at tl (index-aa2b6c04.js:1:6941)
index-aa2b6c04.js:1 TypeError: Cannot read properties of undefined (reading 'getLastStat')
    at index-aa2b6c04.js:46:38150
    at dn (index-aa2b6c04.js:1:14386)
    at sa.l [as fn] (index-aa2b6c04.js:1:19756)
    at sa.run (index-aa2b6c04.js:1:5605)
    at sa.v [as scheduler] (index-aa2b6c04.js:1:20122)
    at tl (index-aa2b6c04.js:1:6941)
    at ri (index-aa2b6c04.js:1:6877)
    at ua (index-aa2b6c04.js:1:12493)
    at sa.scheduler (index-aa2b6c04.js:1:13977)
    at tl (index-aa2b6c04.js:1:6941)
index-aa2b6c04.js:47 Showing container name: undefined, id: 549a055c8a9a
index-aa2b6c04.js:1 TypeError: Cannot read properties of undefined (reading 'id')
    at index-aa2b6c04.js:47:280
    at dn (index-aa2b6c04.js:1:14386)
    at sa.l [as fn] (index-aa2b6c04.js:1:19756)
    at sa.run (index-aa2b6c04.js:1:5605)
    at v (index-aa2b6c04.js:1:20122)
    at al (index-aa2b6c04.js:1:15585)
    at ve (index-aa2b6c04.js:1:42037)
    at sa.V [as fn] (index-aa2b6c04.js:1:41052)
    at sa.run (index-aa2b6c04.js:1:5605)
    at g.update (index-aa2b6c04.js:1:41893)
index-aa2b6c04.js:1 TypeError: Cannot read properties of undefined (reading 'id')
    at l (index-aa2b6c04.js:46:47866)
    at Le.immediate (index-aa2b6c04.js:47:287)
    at dn (index-aa2b6c04.js:1:14378)
    at bt (index-aa2b6c04.js:1:14457)
    at v (index-aa2b6c04.js:1:20183)
    at al (index-aa2b6c04.js:1:15585)
    at ve (index-aa2b6c04.js:1:42037)
    at sa.V [as fn] (index-aa2b6c04.js:1:41052)
    at sa.run (index-aa2b6c04.js:1:5605)
    at g.update (index-aa2b6c04.js:1:41893)
index-aa2b6c04.js:1 TypeError: Cannot read properties of undefined (reading 'state')
    at index-aa2b6c04.js:47:66
    at dn (index-aa2b6c04.js:1:14386)
    at sa.l [as fn] (index-aa2b6c04.js:1:19756)
    at sa.run (index-aa2b6c04.js:1:5605)
    at v (index-aa2b6c04.js:1:20122)
    at al (index-aa2b6c04.js:1:15585)
    at ve (index-aa2b6c04.js:1:42037)
    at sa.V [as fn] (index-aa2b6c04.js:1:41052)
    at sa.run (index-aa2b6c04.js:1:5605)
    at g.update (index-aa2b6c04.js:1:41893)
index-aa2b6c04.js:47 LogEventSource: container changed undefined dead`

Finally, the list of containers is created again, this time with all containers shown with correct names as `Creating container name: <name>, existing: true`, followed by `Showing container name: undefined, id: <hex ID>` again, where the ID is still the ID of the previously selected container (which still no longer exist).
The container name on top of the logs continues to be the same which was locked after I made the F5 refresh.

It's still very unclear to me exactly what's going on, but at least some of the tests above remove some of the random-ness of the part of the issue that has to do with the container name on top of the log.

Going back to `amir20/dozzle:v4.10.0` and performing the same tests, I find the same behavior, including the errors on F5 reloads.

I think there are two (perhaps three), individual issues at play here:

1. The `gitea` name in the container list somehow gets modified to `cottage`.
2. On F5-reloads, the container name on top of the log gets stuck to a name from the modified container list.
3. (unrelated issue), Undefined logs with invalid ID's are attempted shown.


Related to the name change - it gets stranger !!!

I tried renaming my `gitea` container to `agitea`, and then made a new `traefik/whoami` container named `gitea` from within the same docker-compose.yml file.
In Dozzle container list, the new `gitea` container showed up as `cottage`, but to my big surprise the `agitea`  container now shows up as `waved`.
Adding another `traefik/whoami` container named `bgitea` in another docker-compose.yml file just brings up a `bgitea` container in the container list.
Still with the real `gitea` container renamed to `agitea` and the `bgitea` from above renamed to `gitea`, the container list in Dozzle shows the correct container names `gitea` and `agitea` UNTIL an F5-reload (where the locked container name still occur), but where the renaming again occurs in the container list, so `gitea` becomes `cottage`  and `agitea` becomes `waved`.


Phew. This got longer than expected, and still really strange!

**Comment by amir20** [comment] 2023-04-29 14:51
Sorry didn't get a chance to respond yesterday....

> Looking at the verbose output I get Showing container name: undefined, id: <hex ID>, where the ID matches the selected container

This is to be expected because everything on the client is done asynchronously. So log id loads first then I fetch all the containers. 

I need to read everything again, but one thing that stands out is no where in the logs do you see `cottage`, right? Which means that the data from the server or on the client is never manipulated. 

If that is true, then the only logical place would be during rendering some thing changes. 

Can you confirm you don't see incorrect titles in the logs? 

The next step is to do a watch on `container.name` and see if it ever changes and as you suggested start putting comments in HTML to see what happens during rendering. 

My weekends is busy with the kids but hopefully I can find a little time to dive deeper.

**Comment by f-steff** [comment] 2023-04-29 15:45
Thank you! 

I can confirm that I see neither the name `cottage` nor the name `waved` in the verbose output logs.

I'm curious about where the container names are stored for the two places it's used. I would assume you have the names in a sort of string-array in go, and look up the names every time they are used. But the F5-issue (which I assume you can reproduce?) makes me suspect the string-array is stored in, and re-read from, the browser? I didn't really investigate, but it would allow for the renaming to take place only once, which would better separate the issues I described. 

Another thing I just noticed. When fast F5-reloading the page multiple times in a row, I sometimes glimpse the correct container name in the container list, before it's renamed. 

Enjoy the time with your kids. (They grow up so fast!!)

**Comment by amir20** [comment] 2023-04-29 19:43
The container meta data is fetched from Go API. This is what happens. 

1. When Dozzle first loads it [fetches](https://github.com/amir20/dozzle/blob/088d96cb0d8b65c9993a0e285428c6b806a3eeb3/assets/stores/container.ts#L37)  all current containers from the server. It uses event streams. 
2. The event stream remains open and [fetches](https://github.com/amir20/dozzle/blob/088d96cb0d8b65c9993a0e285428c6b806a3eeb3/assets/stores/container.ts#L42) all container cpu and memory data. 
3. When a container dies, it will update the [container status](https://github.com/amir20/dozzle/blob/088d96cb0d8b65c9993a0e285428c6b806a3eeb3/assets/stores/container.ts#L50). 
4. When a new container is started then the API will push all containers again. Note [this is the only](https://github.com/amir20/dozzle/blob/088d96cb0d8b65c9993a0e285428c6b806a3eeb3/assets/stores/container.ts#L39) place container names can change.  Which is why it is weird to see the names change at a later event. 

All the data is stored in a javascript [array](https://github.com/amir20/dozzle/blob/088d96cb0d8b65c9993a0e285428c6b806a3eeb3/assets/stores/container.ts#L7).  While switching between pages, a single page is loaded and the page is rendered. Nothing is updated in to the container list except when the API pushes new updates. 

> But the F5-issue (which I assume you can reproduce?) makes me suspect the string-array is stored in

No I have not been able to reproduce this. That's the hard part. I also don't have a Windows machine which makes me wonder if it is related to the OS. 

> Another thing I just noticed. When fast F5-reloading the page multiple times in a row, I sometimes glimpse the correct container name in the container list, before it's renamed.

But this makes no sense because the logs show that no data is updated with the wrong name. 

Dozzle is used thousands time a day so I would expect more people to see this error if it was consistent. 

You said earlier that same setup on a different machine does not reproduce this issue, right? Is there anything different? 

In the bug, you also mentioned that it happens consistently with safari, chrome and edge. But we ruled out any API changes that would trigger a name change via the logs. 

So I am puzzled. I don't know what logging to add to help us reproduce.

**Comment by amir20** [comment] 2023-04-29 19:48
> Another thing I just noticed. When fast F5-reloading the page multiple times in a row, I sometimes glimpse the correct container name in the container list, before it's renamed.


When this happens, do you see `Showing container name: XXXX, id: YYYY`? That log is explicitly watching for `container.name`. So if it doesn't change from the real value to "cottage" it means JS sees no changes to data.

**Comment by amir20** [comment] 2023-04-29 19:58
I added another logging in df76b2f. This one should print `Found container from store name: XXXX` which should be a level nested after fetching the right container. This object is also the object that gets injected in all other components. So maybe it will give us a clue.

**Comment by f-steff** [comment] 2023-04-29 20:01
When I glimpse the renaming happening it's right after pressing F5 to reload the entire page. I do not see a `Showing...` debug message with first the correct name and then the incorrect name. I see exactly the same things as described in my previous description.

**Comment by amir20** [comment] 2023-04-29 20:08
At this point, I have to rule out any changes to the state of data. The problem is that all the rendering is done by VueJs. I don't even know to check Vue's rendering logic.

**Comment by f-steff** [comment] 2023-04-29 20:15
I see. 

Well, if you manage a new release (tag) soon, I can have some feedback to you very quick. (Still only 22:15 here)

**Comment by amir20** [comment] 2023-04-29 20:21
All PRs and `master` are auto pushed on any commit. So you should be able to do `docker pull amir20/dozzle:pr-2158` to get the latest version. 

But I have a feeling you won't see any new insights based on what you've seen so far....

To me, it doesn't make sense that you can reproduce on more than one browser meaning it should be an API bug. But based on the logs the names are never updated. So it should be on client only. Even if I was sitting in front of your computer I would be stumped.

**Comment by f-steff** [comment] 2023-04-29 21:17
Ahh, thank you for that explanation. I'm used to a CI setup where every public release gets a new serial number, so I didn't expect the same tag to be updated.

With the latest version of `amir20/dozzle:pr-2158` something really strange happened: All the visual issue I have seen disappeared. Going back to `amir20/dozzle:v4.10.0` they reappear. I guess your debug printing pushed something. Might be a race-condition somewhere.

Loading `https://dozzle.internal.company.com/` I get 11 times `Creating container name: <name>, existing: false`, and see the two container lists.

Clicking on `dozzle`, I get `Showing container name: dozzle, id: 09bf621eb08b` followed by `Found container from store name: dozzle, id: 09bf621eb08b`. The container list still contains all the correct names, and the log is correctly shown.

Pressing F5, I get `Showing container name: undefined, id: 09bf621eb08b` followed by `Found container from store name: undefined, id: 09bf621eb08b`, followed by 11 times `Creating container name: <name>, existing: false`, and finally `Showing container name: dozzle, id: 09bf621eb08b` followed by `Found container from store name: dozzle, id: 09bf621eb08b. Again the container list still contains all the correct names, and the log is correctly shown.

Clicking on `gitea`, I get `Showing container name: gitea, id: e96752499297`, followed by `Found container from store name: gitea, id: e96752499297`. Again the container list still contains all the correct names, and the log is correctly shown.

Bringing down `gitea`, I get `LogEventSource: container changed dead running`, and the `gitea` entry in the container list disappears. The log remains visible.

Bringing up  `gitea` again a lot of things are happening: 10 times `Creating container name: <name>, existing: true` and 1 times `Creating container name: gitea, existing: false`. Then 2 times the `getLastStat` TypeError (Same as before), then `Showing container name: undefined, id: 02c16c1eb11c` and `Found container from store name: undefined, id: 02c16c1eb11c` before two more TypeErrors for `id` and one for `state` (Also same as before). Then `LogEventSource: container changed undefined dead`, before 11 times `Creating container name: <name>, existing: true` and finally `Showing container name: undefined, id: 02c16c1eb11c`. After all of this the container list still contains all the correct names, but the log is blank.

If I bring up  `gitea` while `dozzle` log is shown, I get 10 times `Creating container name: <name>, existing: true` and 1 time `Creating container name: gitea, existing: false`.  Then `Showing container name: dozzle, id: 09bf621eb08b`. Then 11 times `Creating container name: <name>, existing: true` and finally `Showing container name: dozzle, id: 09bf621eb08b`.

All in all, I simply can't trigger any of the issues with the latest version of `amir20/dozzle:pr-2158`

**Comment by amir20** [comment] 2023-04-29 21:37
There were some changes to master and I did a rebase. Hmmm I need to a diff to see if something else changed. I'll follow up tomorrow.

**Comment by amir20** [comment] 2023-04-29 21:44
Comparing 4.10 with the latest can be found at https://github.com/amir20/dozzle/compare/v4.10.0...debug-logs. The only difference that could impact this is I have updated vue and vue plugins. 

Well, I am glad we can't reproduce it. Maybe 4.10.0 was just a bad build.  

Please try the latest `4.10.3` and hope it doesn't come back!

**Comment by f-steff** [comment] 2023-04-29 22:49
I've made an extensive test of `amir20/dozzle:v4.10.3`, and can't trigger any of the issues with that version either, so it seems like it's "fixed"... I guess that's good news, although I really would have liked to pinpoint the cause of this problem. 
As you said, "the most interesting bug I have seen for a while", and I can't agree more.

Thank you so much for your time. It was a pleasure hunting with you.

**Comment by amir20** [comment] 2023-04-29 22:51
If you have time, you could try 4.10.1 and 4.10.2. 😬 then I can pin point to the specific commit. Sent via my iPhoneOn Apr 29, 2023, at 3:49 PM, Flemming Steffensen ***@***.***> wrote:﻿
I've made an extensive test of amir20/dozzle:v4.10.3, and can't trigger any of the issues with that version either, so it seems like it's "fixed"... I guess that's good news, although I really would have liked to pinpoint the cause of this problem.
As you said, "the most interesting bug I have seen for a while", and I can't agree more.
Thank you so much for your time. It was a pleasure hunting with you.

**Comment by f-steff** [comment] 2023-04-29 22:53
👍 Will do. Tomorrow.

**Comment by f-steff** [comment] 2023-04-29 23:09
Nah... Couldn't resist. Had to know.

I see the issues in 4.10.0 and 4.10.1, and did in the first version of 2158.

After a quick test I do not see the issues in 4.10.2, 4.10.3, and the current version of 2158.

**Comment by amir20** [comment] 2023-04-30 19:19
I installed `v4.1.0.0` a few times and couldn't reproduce. 

Delta between .1 and .2 is minimal. There is only two [significant changes](https://github.com/amir20/dozzle/compare/v4.10.1...v4.10.2). The only thing that _could_ have affected this is the update of `plugin-vue`. But looking through the [changelog](https://github.com/vitejs/vite-plugin-vue/blob/main/packages/plugin-vue/CHANGELOG.md) I see nothing that could explain this. 

I was really hoping to be able to explain how a random text appears. But doesn't look like it.

**Comment by f-steff** [comment] 2023-04-30 20:17
Thank you for the extra effort.
I've not spend any time on it today, but still believe it is two separate issues related to some sort of array corruption. It's only ever happened on one of my machines, so it might simply be a really unlikely coincidence that triggered it. The vue update was probably what fixed it. 
For now I don't think we can get closer to what happened, but going forward I'll keep an extra eye on Dozzle. 😀

**Comment by amir20** [comment] 2023-05-01 15:18
I agree. Closing for now. Hoping I can see this happen on my side, but for now can't do much about it.

**Closed by amir20** 2023-05-01 15:18 UTC
