### ISSUE TITLE
improve management of timestamp in multiline logs

### ISSUE THREAD

**Issue by FrancYescO** [amir20/dozzle#2967] opened 2024-05-22 07:25 UTC
when a container write a multiline log (i.e. java stacktrace...), will be a little difficult to copy a clear log as timestamp will be placed 
in front of each line

i know there is the "show timestamp" flag in settings, but is not very convenient to use while having to deal with different container writing different log format

```
20/05/2024
17:33:52
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[catalina.jar:10.1.24]
20/05/2024
17:33:52
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389) ~[tomcat-coyote.jar:10.1.24]
20/05/2024
17:33:52
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:10.1.24]
20/05/2024
17:33:52
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-coyote.jar:10.1.24]
20/05/2024
17:33:52
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-coyote.jar:10.1.24]
20/05/2024
17:33:52
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-coyote.jar:10.1.24]
20/05/2024
17:33:52
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) ~[tomcat-util.jar:10.1.24]
20/05/2024
17:33:52
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:10.1.24]
20/05/2024
17:33:52
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-util.jar:10.1.24]
20/05/2024
17:33:52
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

possible solutions:
- find a way to detect that it's a multiline and just write a single timestamp (this will also help to get a cleaner ui instead of repeating timestamp text)
- add a setting to "exclude timestamp" while selecting the log text
- if ms of timestamp are the same just avoid the reprint of timestamp (looks more as an hacky workaround)

**Additional context**
<img width="1193" alt="image" src="https://github.com/amir20/dozzle/assets/4574593/bdb06e7d-b30d-461e-a376-a4adaab76cc6">

**Comment by amir20** [comment] 2024-05-22 23:50
Hmm yea, interesting problem. Ideally that whole block would have one copy icon (which should in https mode). I am thinking of grouping these logs better but that's not happening right now. 

I can't think of an easy short term solution. 

You could temporary disable timestamps in settings, but that's not great. 

> find a way to detect that it's a multiline and just write a single timestamp (this will also help to get a cleaner ui instead of repeating timestamp text)
> if ms of timestamp are the same just avoid the reprint of timestamp (looks more as an hacky workaround)

Both of these solutions require the groups to be done as one atomic log item which is not done today.

**Comment by amir20** [comment] 2024-05-24 14:58
I don't have any immediate plans to fix this as it would require a big change. Closing for now. 

If anybody wants to help out with a PR then it would be greatly welcomed.

**Comment by FrancYescO** [comment] 2024-05-29 12:57
just as fast improvement, seems adding `user-select: none;` as css to
https://github.com/amir20/dozzle/blob/e00af4321f6a99133250df2aba932129997c9704/assets/components/LogViewer/LogDate.vue#L2

can help to at least select log content whiteout having the date messing around :D

**Comment by amir20** [comment] 2024-05-29 13:00
Ohhh good idea. I'll try it.

**Comment by amir20** [comment] 2024-05-29 15:19
Beautiful solution.  🚀

**Comment by FrancYescO** [comment] 2024-05-29 15:41
as a perfect solution i love to see a not repeated date when is a complex log (in this case having the date selectable can be useful), but didn't find the right spot to have this thing done :D

**Comment by amir20** [comment] 2024-05-29 15:44
Perfect solution with minimal amount of work? 😁 Not repeating dates is something I plan to do long term. When streaming multiple logs, they stream in parallel and sometimes the logs are mixed together which I don't think is a great experience. So I plan to do something like `GroupedLogs` where it would do grouping of similar logs and levels. The problem is a lot of multi-threaded code is happening so it is very complicated to get it right.

**Comment by amir20** [comment] 2024-05-29 15:45
Merged the PR.

**Closed** 2024-05-29 15:45 UTC
Labels: enhancement

**Comment by FrancYescO** [comment] 2024-06-25 00:25
Hello @amir20 .... a little fix is needed here stout/sterr is still selected

<img width="392" alt="image" src="https://github.com/amir20/dozzle/assets/4574593/0e6e6bc4-ff81-46ee-9050-5627f1758e32">
