### ISSUE TITLE
Feature Enhancements

### ISSUE THREAD

**Issue by STaRDoGG** [amir20/dozzle#172] opened 2019-11-06 22:54 UTC
Just installed Dozzle and very cool and useful. =)

Right off the bat I notice something that it seems to be missing that would make it much more useful and "powerful"; the ability to split the main window into smaller ones, and open other logs in them. 

i.e.  open up 2 different logs side by side, or 4 separate logs in 4 smaller "windows", all on the same screen, so you can monitor more than 1 log at a time if/when needed.

--

The ability to change the font sizes and colors as well. (without having to hack the .css ourselves)

--

And also, the ability to have better automatic coloring of the contents of the logs to make things easier to quickly glean info from at quick glances. Maybe some RegEx adding ability?

**Comment by amir20** [comment] 2019-11-06 23:43
> i.e. open up 2 different logs side by side, or 4 separate logs in 4 smaller "windows", all on the same screen, so you can monitor more than 1 log at a time if/when needed.

I have been thinking about this for a while as a few other people have asked for this feature. One idea was to show multiple logs intertwined within the log view. I felt this was confusing as now I need to introduce a notion of stickyness, labeling of container id, etc...

I hadn't thought about your idea with multiple windows. Do you have an idea on how that would work? Is there a button that would make it create a window vertically? I am trying visualize what could be the idea and struggling to come up with anything that is actually easy to use. 

> The ability to change the font sizes and colors as well. (without having to hack the .css ourselves)

I am adding a "settings" page which should be able to add this functionality. 

> And also, the ability to have better automatic coloring of the contents of the logs to make things easier to quickly glean info from at quick glances. Maybe some RegEx adding ability?

Hmm I have to think about this one. Short of having hundreds of regex configurations, I am not sure how else to do that. I have to also think about performance. Some of my logs are producing 100s of lines per minute so after 10 minutes that's a lot for the browser to refresh if needed.

**Comment by amir20** [comment] 2019-11-06 23:43
And of course, thanks for the feedback!

**Comment by STaRDoGG** [comment] 2019-11-07 00:22
> I have been thinking about this for a while as a few other people have asked for this feature. One idea was to show multiple logs intertwined within the log view. I felt this was confusing as now I need to introduce a notion of stickyness, labeling of container id, etc...
> 
> I hadn't thought about your idea with multiple windows. Do you have an idea on how that would work? Is there a button that would make it create a window vertically? I am trying visualize what could be the idea and struggling to come up with anything that is actually easy to use.

I agree that intertwining all logs would be very confusing and messy. I've never created split views myself so I can't directly be helpful in that area, but I would imagine there are plenty of nice frameworks already out there that are ready to use. A quick search came up with this, which might be nice:

https://split.js.org


> 
> > The ability to change the font sizes and colors as well. (without having to hack the .css ourselves)
> 
> I am adding a "settings" page which should be able to add this functionality.

Perfect. =)

> > And also, the ability to have better automatic coloring of the contents of the logs to make things easier to quickly glean info from at quick glances. Maybe some RegEx adding ability?
> 
> Hmm I have to think about this one. Short of having hundreds of regex configurations, I am not sure how else to do that. I have to also think about performance. Some of my logs are producing 100s of lines per minute so after 10 minutes that's a lot for the browser to refresh if needed.

There are several log viewer apps out there that already use regexes to highlight, so an idea might be to download them and just copy their regexs and replicate them in Dozzle. =)

i.e. https://retrospective.centeractive.com/

which ends up looking like this:

https://d2.alternativeto.net/dist/s/f1379e88-cc03-e211-a494-0025902c7e73_4_full.png?format=jpg&width=1600&height=1600&mode=min&upscale=false

I think a few basic regexes shouldbt be too bad? Would only really know after testing.

**Comment by amir20** [comment] 2019-11-18 23:58
@STaRDoGG just an update of what I have done so far. I did a lot of work to be able to split the view now. It's still work in progress but I think a good start. I am going to share a video to see what you think.

![dozzle](https://user-images.githubusercontent.com/260667/69104131-3901c200-0a1c-11ea-81b7-9f2e53d4cc46.gif)

**Comment by STaRDoGG** [comment] 2019-11-19 01:20
@amir20 That's *perfect*. Exactly what I was hoping for. Thank you for working on it! =)

**Comment by amir20** [comment] 2019-11-25 23:28
@STaRDoGG try `v1.17.0` that should allow you to split panes via the thumbtack icon on the menu. There is still going to be bugs I am sure. But I'll take a look after this week.

**Comment by STaRDoGG** [comment] 2019-12-13 17:47
Heyas @amir20 

Been using the new version a bit more lately (found some free coding time) and notice a couple other tweaks that would be helpful.

![image](https://user-images.githubusercontent.com/1524526/70820064-54eb5000-1d9d-11ea-87b9-196934365d1d.png)

**From left to right:**
- I noticed there's quite a bit of usable log space being occupied by the container list on the left, being occupied by blank space. Perhaps size it via the width of the longest container name + a few extra px/em?
- When selecting the first log (without pinning) it doesn't have a header showing it's log name like you do get when pinning a log. It would be nice to have a header for it as well. =)
- The header with the name in it disappears when scrolling down, and to see it again you have to scroll all the way back up. I often glance up in a log out of habit to see which log I'm looking at. It helps when you're bouncing in and out of different apps while coding, to just be able to look up and remind yourself "where you're at". Perhaps set the header to `position: fixed` or similar? (I didn't try it myself yet)

**Comment by amir20** [comment] 2019-12-13 20:21
Thanks @STaRDoGG!

> I noticed there's quite a bit of usable log space being occupied by the container list on the left, being occupied by blank space. Perhaps size it via the width of the longest container name + a few extra px/em?

Can you update to `v1.18`? I released it this week which adds support for flexible menu width. This allows the space to be whatever the user wants.  It would be too hard to do `Perhaps size it via the width of the longest container name` because I don't actually know how much space it would take. 

> When selecting the first log (without pinning) it doesn't have a header showing it's log name like you do get when pinning a log. It would be nice to have a header for it as well. =)

That's to be expected right? A header is not needed since the left menu shows what is currently selected.  The left section is always the primary view port which I assume the majority user will use. 

> The header with the name in it disappears when scrolling down, and to see it again you have to scroll all the way back up. I often glance up in a log out of habit to see which log I'm looking at. It helps when you're bouncing in and out of different apps while coding, to just be able to look up and remind yourself "where you're at". Perhaps set the header to position: fixed or similar? (I didn't try it myself yet)

That seems to be a bug. It's set to `flex: column` so it shouldn't scroll because the scroll is actually below the header.  What browser are you using? In Chrome, I can't reproduce this.

**Comment by STaRDoGG** [comment] 2019-12-14 01:40
Hi Amir

Looks like ya beat me to it! lol. I didn't realize there was a newer version, so I updated and it looks like 2 of the 3 I mentioned are already taken care of. =)

The header stays in place now when I scroll, which is awesome, and when resizing the left border it automatically stops at the exact place it needs to be if I just try to drag it as far left as it will go; only minor issue is it loses that position after reloading dozzle. It'd be kinda sweet if it just automatically placed that left border there upon load. And then perhaps set/read from a cookie to save/restore any user positioning? Just a thought.

Regarding the lack of a header for the 'main' (first, or unpinned) log, I suppose you're right; it's easy enough to just look left. I guess I'm just in the habit of always looking up at the header, as well as thinking it'd be a bit more of a consistent look if all log windows had that header at the top (when more than 1 log is open; if only 1 log is open, the header isn't really all that necessary).

**Comment by amir20** [comment] 2019-12-16 21:50
@STaRDoGG yup! I am actively working on this project so I am releasing updates every few weeks. 

> It'd be kinda sweet if it just automatically placed that left border there upon load.

That's coming...I am waiting to implement settings page as we discussed and have that as an option. 

> well as thinking it'd be a bit more of a consistent look if all log windows had that header 

I am not completely against putting header. One option would be to put header when there is more than 1 pane. 

I am currently working on a few new features. Here is what I am doing first:

1. Being able to scroll up and loading previous logs. (This is a lot harder than expected)
2. Adding settings page
3. Fixing perf issues 

Once I have some of this done, I will revisit the headers. 

Question for you: What do you think about the UI far to create new panes? TBH, I don't love it. I am not a designer but I couldn't come up with a better idea than a thumbtack. It looks lame IMO. If you know of a better way to create a new pane, then I am all ears. 

I'll close this ticket and create the settings page under another PR.

**Comment by amir20** [comment] 2019-12-16 21:50
Closing and tracking the rest under new tickets.

**Closed by amir20** 2019-12-16 21:50 UTC

**Comment by STaRDoGG** [comment] 2019-12-17 21:32
> Question for you: What do you think about the UI far to create new panes? TBH, I don't love it. I am not a designer but I couldn't come up with a better idea than a thumbtack. It looks lame IMO. If you know of a better way to create a new pane, then I am all ears.

Personally, I don't think it looks too bad. The "pins" (if being nitpicky) might seem a bit weird, but again, not a big deal to me.

I'm not the greatest designer myself, but the only things I can really think of offhand might be the ability to choose color schemes (you're probably already on that, with the Settings page), and perhaps a way to choose the layout when multiple panes are open. For example, if more than 3 panes, give the ability to open the logs in a quad view (like a cross shape) rather than all of the logs showing in a vertical view.

If any other ideas come to mind I'll definitely revisit this thread and post them. =)

**Comment by amir20** [comment] 2019-12-18 00:22
Sounds good. Scrollback infinite loading is live now in `v1.19.x`.  And some performance stuff has been fixed. So I'll try to come back to some more things in this thread later this week.

**Comment by amir20** [comment] 2020-01-01 00:38
@STaRDoGG I have created a setting page which is accessible on the desktop. It's still bare right now. But I'll be adding more options in the future.

**Comment by STaRDoGG** [comment] 2020-01-01 06:22
@amir20 I just fetched the latest today; I'm loving the new changes/enhancements.

**Comment by amir20** [comment] 2020-01-02 02:35
Nice @STaRDoGG. Thanks again for your suggestions. I have a few bugs to work on but will be back to more features soon.
