### ISSUE TITLE
healthcheck return error when you change --addr

### ISSUE THREAD

**Issue by lord007tn** [amir20/dozzle#3438] opened 2024-12-05 12:30 UTC
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.8.2

### ✅ Command used to run Dozzle

dozzle:
    image: amir20/dozzle:latest
    command:
      - "--addr"
      - ":9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    labels:
      - 'traefik.enable=true'
      # Service definition
      - 'traefik.http.services.dozzle.loadbalancer.server.port=9000'
      # HTTPS Router
      - 'traefik.http.routers.dozzle.rule=Host(`dozzle-staging.iqraamkh.com`)'
      - 'traefik.http.routers.dozzle.entrypoints=websecure'
      - 'traefik.http.routers.dozzle.tls=true'
      - 'traefik.http.routers.dozzle.tls.certresolver=myresolver'
      - 'traefik.http.routers.dozzle.service=dozzle'
    networks:
      - default
      - monitoring
      - elk
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5

### 🐛 Describe the bug / provide steps to reproduce it

healthcheck always returns an error and that leads to traefik cant expose the application 
this is the result when i run health check manually:
```
azureuser@iqraa-staging:~$ docker exec -it azureuser-dozzle-1 /dozzle healthcheck
{"level":"info","url":"http://localhost:8080/healthcheck","time":"2024-12-05T12:23:27Z","message":"performing healthcheck"}
{"level":"fatal","error":"Get \"http://localhost:8080/healthcheck\": dial tcp [::1]:8080: connect: connection refused","time":"2024-12-05T12:23:27Z","message":"Failed to make request"}
```
and this is the log after running the dozzle docker image 

```
dozzle-1  | {"level":"info","time":"2024-12-05T12:24:26Z","message":"Dozzle version v8.8.2"}
dozzle-1  | {"level":"info","clients":1,"time":"2024-12-05T12:24:26Z","message":"Connected to Docker"}
dozzle-1  | {"level":"info","time":"2024-12-05T12:24:26Z","message":"Accepting connections on :9000"}

```

as you can see the app listen on the port 9000 and health check is hardcoded to port 8080

### 💻 Environment

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 13
  Running: 10
  Paused: 0
  Stopped: 3
 Images: 14
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-1016-azure
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.703GiB
 Name: iqraa-staging
 ID: 327aa31c-d7cf-4dce-a2d7-88f48700c89f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by amir20** [comment] 2024-12-05 16:00
Yes, this is a bug. However, if you use `DOZZLE_ADDR` instead, it should work. The issue is that `--addr` is not available for the `healthcheck` command, while `DOZZLE_ADDR` is visible, allowing the healthcheck command to use it.

By the way, why are you overwriting the address? Port 8080 should work just fine. Even within a Traefik network, `8080` is only used to communicate with a specific container.

I plan to remove support for `--addr` because fewer than 1% of users are utilizing it, and I don't understand why anyone would need it.

**Comment by amir20** [comment] 2024-12-05 16:00
Closing since there is a work around with `DOZZLE_ADDR`.

**Closed by amir20** 2024-12-05 16:00 UTC
Labels: bug
