### ISSUE TITLE
Horizontal scroll snaps back on Firefox

### ISSUE THREAD

**Issue by Coteh** [amir20/dozzle#1728] opened 2022-04-27 14:11 UTC
**Describe the bug**
Seems to only happen on Firefox. If you scroll a non-soft wrapped pane horizontally to the right, it will snap back to the left.

**To Reproduce**
1. Turn off soft wrap in settings
2. Click on any container
3. Reduce width of window or split pane and reduce width of left pane
4. Scroll pane horizontally

**Expected behavior**
Pane should scroll and remain in place on Firefox.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Docker version [e.g. `docker version`'s output] `Docker version 20.10.7, build f0df350`
 - Browser & version [e.g. chrome, safari] Firefox 99.0.1 (64-bit)
 - Version [e.g. 1.26.1. Can be found at `<Dozzle-host>/version`] 48d34f3f58e9070879f7245ee70f6dda3b1a11f0

**Comment by amir20** [comment] 2022-04-27 20:41
I was able to reproduce this. That is the weirdest bug I have ever seen. It's even animated while scrolling back.

**Comment by Coteh** [comment] 2022-05-14 16:13
One thing I noticed: If there's logs being printed and you hold the scrollbar in place while scrolling, the scrollbar will automatically snap back before you let go. However, if there's no more logs being printed, you can hold the scrollbar in place and it won't snap back until you let go.

I wonder if the former is due to the `events` container rerendering. But the latter... not sure yet.

**Comment by amir20** [comment] 2022-07-27 16:38
I am going to close this since no one has really said anything about this bug.

**Closed** 2022-07-27 16:38 UTC
Labels: bug, pinned
