### ISSUE TITLE
Problem with log printing

### ISSUE THREAD

**Issue by nailuox** [amir20/dozzle#2261] opened 2023-06-19 06:52 UTC
**Describe the bug**
Hello, now I have a large input data for an interface. When printing logs, I found that the value of one parameter was inserted as a date. Please take a look at the screenshot below.

**To Reproduce**

**Expected behavior**
I hope that the log output can show the correct input data.

**Screenshots**
![image](https://github.com/amir20/dozzle/assets/49058926/aa51d05f-4a4c-4e38-a95c-154a42280491)
![image](https://github.com/amir20/dozzle/assets/49058926/9e3e85a7-52b0-4bfc-9315-9abe4f9f20db)

**Desktop (please complete the following information):**

- OS: [linux]
- Docker version [19.03.8]
- Browser & version [chrome]
- Version [latest]

**If applicable include logs with `--level debug` and browser logs**
Hello, now I have a large input data for an interface. When printing logs, I found that the value of one parameter was inserted as a date. Please take a look at the screenshot below.

**Comment by amir20** [comment] 2023-06-19 13:12
I am confused at these screenshots. They don't look like Dozzle. The bug also doesn't make sense. Dozzle doesn't change any data. Are you sure the problem is Dozzle? Can you provide the right screenshots

**Comment by amir20** [comment] 2023-06-21 15:19
Haven't heard back....

Closing

**Comment by nailuox** [comment] 2023-06-27 07:50
Sorry for not responding in a timely manner. Below is a detailed screenshot
![image](https://github.com/amir20/dozzle/assets/49058926/2ec5fbeb-af97-47fc-be0d-3ad87acf771a)

**Comment by nailuox** [comment] 2023-06-27 07:51
@amir20 
 Sorry for not responding in a timely manner. Below is a detailed screenshot
![image](https://github.com/amir20/dozzle/assets/49058926/793bf490-3f68-431f-b2d8-f3ba442c21e9)

**Comment by nailuox** [comment] 2023-06-27 07:52
@amir20
Sorry for not responding in a timely manner. Below is a detailed screenshot
![image](https://github.com/amir20/dozzle/assets/49058926/0ae9c385-99dc-4f15-9dd4-d13244018c17)

**Comment by amir20** [comment] 2023-06-28 19:33
I haven't been able to reproduce this so I am afraid I can't help much...

**Comment by nailuox** [comment] 2023-06-30 03:16
I changed the size of the buffer and repackaged it without any problem
```go
// log_iterator.go file
func NewEventIterator(reader *bufio.Reader) *eventGenerator {
	generator := &eventGenerator{reader: reader, channel: make(chan *LogEvent, 500)}
	go generator.consume()
	return generator
}
```

**Comment by amir20** [comment] 2023-06-30 03:33
Interesting. I have to take a look to see what can cause that.

**Comment by nailuox** [comment] 2023-06-30 03:49
It is possible that the parameter data is too large, and this interface parameter has nearly 200kb

**Comment by amir20** [comment] 2023-07-06 19:50
Ok to be honest I have no idea what could be causing this problem. But looking at the bug,  perhaps the way STDERR and STDOUT are read could be cleaned up so that such error never happens. 

I'll have to keep thinking about this.  Sorry no immediate solution.

**Comment by amir20** [comment] 2023-07-07 18:32
@nailuox can you please try `amir20/dozzle:pr-2295`? In #2295 I have updated some logic that should be cleaner.

**Comment by amir20** [comment] 2023-07-10 16:26
This causes a different bug which I'll have to look into. So I'll have to close this and come back to it later.

**Closed** 2023-07-10 16:26 UTC
