### ISSUE TITLE
Unable to see logs

### ISSUE THREAD

**Issue by natraj09** [amir20/dozzle#13] opened 2019-02-01 20:52 UTC
I am unable to see logs of few of the containers.  The logs do show up when I simply run the command `docker logs <container-id>`.  How do I trouble shoot this?

**Comment by amir20** [comment] 2019-02-02 16:18
I haven't been able to reproduce this. A couple of questions: 

1. Does this happen to all containers or just a few? I am trying to figure out if it is a firewall issue or something
2. What browser are you using? Are you using swarm or anything? 
3. Can you open browser console and see if there are any javascript errors? 
4. Does the logs for Dozzle show anything?

**Comment by amir20** [comment] 2019-02-02 16:18
@natraj09 See if you can answer these questions

**Comment by natraj09** [comment] 2019-02-04 21:34
@amir20 
See my response below

1. It only happens on few of them. I have a nginx docker container where I am able to see logs of incoming request. The logs also appear for the dozzle container.
2. I am using Chrome browser.  Using only docker to run containers. 
3. No errors
4. Yes . I see this
`last Friday at 3:41 PM level=info msg="Dozzle version 1.5.8"
last Friday at 3:41 PM level=info msg="Accepting connections on :8080"`

**Comment by amir20** [comment] 2019-02-04 21:35
@natraj09 I am not sure what the problem can be. I need to be able to reproduce it. What are you running and is there a way for me to reproduce it?

**Comment by natraj09** [comment] 2019-02-04 21:41
@amir20 
I dont have a way to share the application.  It's a spring boot application.
I also have this docker settings in daemon.json
`{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m",
    "max-file": "5"
  }
}`
Does this matter?

**Comment by amir20** [comment] 2019-02-05 22:19
@natraj09 I stood up a spring app and it worked. I think I am out of ideas. Sorry! My best guess is that something is not right with your log driver.

**Comment by amir20** [comment] 2019-02-16 23:18
@natraj09  I am going to close this as I can't reproduce it. I forgot to tell you that you can change logging level with `--level debug`. Maybe that will help.

**Closed by amir20** 2019-02-16 23:18 UTC

**Comment by Fzibi21** [comment] 2022-04-30 20:15
I have the issue that the logs are not showing up on any container on my PX regardless which browser is used.  it says that there are 0 containers running.  
Wrenn i look at the same Dozzle instance on my phone does it show correctly. 
Any ideas on that ?
