### ISSUE TITLE
Access containers by providing names in the URL, in addition of container IDs

### ISSUE THREAD

**Issue by pataquets** [amir20/dozzle#2496] opened 2023-11-13 19:43 UTC
Congratulations on such a great, simple and powerful tool. And thanks for sharing it, it is awesome!

**Is your feature request related to a problem? Please describe.**
If you recreate containers keeping their names, URLs are no longer valid even if the containers have the same names, since the URLs use the container IDs. So, if you recreate containers, "just refreshing" is not enough. This would enable a quick `F5` reload workflow each time you recreate, instead of having to click again the newly created container.

**Describe the solution you'd like**
Either accepting `/container/<container-name>` or an alternative path `/container-by-name/<container-name>`.

**Describe alternatives you've considered**
I couldn't come up with any.

**Additional context**
Using it for a local development stack based in Docker Compose.

**Comment by amir20** [comment] 2023-11-13 20:46
Thanks!

https://dozzle.dev/guide/faq#we-have-tools-that-uses-dozzle-when-a-new-container-is-created-how-can-i-get-a-direct-link-to-a-container-by-name should help. 

As for after the container has stopped, Dozzle will automatically follow to the container with the same name. You don't need to do anything. Assuming you have the right version, this option should be enabled in settings.

**Comment by amir20** [comment] 2023-11-15 16:43
Haven't seen a response. I think the issue is addressed so closing.

**Closed by amir20** 2023-11-15 16:43 UTC
Labels: enhancement

**Comment by pataquets** [comment] 2023-11-15 18:49
Thanks for the quick response @amir20! Also, my apologies, since I totally failed to see this in the docs.
However, this has a minor caveat which sort of contributes to keeping the initial post annoyance: as soon as you navigate the URL, you get redirected to a `/container/ID` URL replacing you browser's URL, thus defeating the "quick-one-key-F5-refresh-when-recreate" trick.
Admittedly, you can place this in a bookmark, but you can't bind shortcut keys for bookmarks (at least in plain Firefox). Just one click, which is an improvement to having to browse for the container again, but not perfect for us keyboard junkies. :smile: Any suggestion?
Thanks a lot for your help.

**Comment by amir20** [comment] 2023-11-15 19:39
Did you see my second comment? 

> As for after the container has stopped, Dozzle will automatically follow to the container with the same name. You don't need to do anything. Assuming you have the right version, this option should be enabled in settings.

Dozzle will automatically go to the next container if found. This was discussed in https://github.com/amir20/dozzle/issues/2376 with some screenshots. I think it's what you want. 

I don't think Dozzle can have `/container/NAME` because names are not unique across different states, eg. if you kill a container and recreate a container it will have the same name but different id. So which one would Dozzle show?

**Comment by pataquets** [comment] 2023-11-15 22:33
OMG! It works, indeed. Even better that I imagined: no refreshing necessary! This tool is truly awesome.
I read your comment, but turns out I was using some pre-5.x version :facepalm: The linked issue gave me the missing clue.
My apologies for wasting your time and sorry for the noise.
Thank you very much.

**Comment by amir20** [comment] 2023-11-15 22:48
> but turns out I was using some pre-5.x version

which is why now in the latest version I have a notification center. :) 

Glad it works!
