### ISSUE TITLE
Running stacks in sidebar or filter by Stack

### ISSUE THREAD

**Issue by BaccanoMob** [amir20/dozzle#2866] opened 2024-04-01 22:58 UTC
Is it possible to display containers based on stack or the compose file?

Say I have a compose file with traefik, authelia, ldap and redis. When I run that file, I want a `running stacks` above `running containers` so I can view logs/containers by compose file/stack. 

Currently it displays all the containers in the host. Implementing this feature will be helpful when debugging containers from a specific file.

Alternatively, you can include a column `stack` similar to portainer and sorting by stack should group the containers together. I would still prefer by filtering by stack since it will be helpful for people running more stacks and want look at only couple of containers in a single docker compose file (like when debugging or when a couple of containers don't start, etc)

**Comment by amir20** [comment] 2024-04-01 23:01
This is basically same as https://github.com/amir20/dozzle/issues/2862

Not sure what has happened but a lot of people are asking for the same thing this week.

**Comment by BaccanoMob** [comment] 2024-04-01 23:31
> Not sure what has happened but a lot of people are asking for the same thing this week.
Prolly a popular feature you should put some thoughts into it perhaps?

Not exactly the same (but similar maybe)... I just want group/filter by containers in the same host which should be easier to implement if docker API supports it (prolly should since portainer does have that option). Btw when I said group by I didn't mean to unify the logs as similar to `docker compose logs` but just have the table with only the involved containers. So it's like `different service in same host`.

Other post #2862 involves multiple host and grouping them which I think will make you rewrite a lot of code since currently dozzle displays by host not by service. (Correct me if I'm wrong, saying with my little knowledge of swarm and k8s). So it's like `same service but different host`.

**Comment by amir20** [comment] 2024-04-01 23:36
It would be too difficult to group and show different containers. Docker API already supports services across hosts which is why I think it would be easier given I am just using Docker API.

**Comment by amir20** [comment] 2024-04-02 17:07
Closing this in favor #2862. If I do end up supporting this it would be through services API and then grouping with `namespace` configuration which has the stack data.

**Comment by amir20** [comment] 2024-04-03 15:40
Please follow the other issue as I have asked questions there.

**Comment by jordanlambrecht** [comment] 2024-04-11 18:43
> It would be too difficult to group and show different containers. Docker API already supports services across hosts which is why I think it would be easier given I am just using Docker API.

Could you group by labels, then? I.e. if someone adds a label like "dozzle.{{container_name}}.group.name: "this is my group" to a service, it knows to stack them together. [AutoKuma](https://github.com/BigBoot/AutoKuma) does a good job with this.

**Comment by amir20** [comment] 2024-04-11 18:57
That's just the grouping in the UI. The bigger problem is showing all the logs within a group. I could open a connection with `tail` for each container. But then I feel I am re-creating Swarm 🤔

**Comment by amir20** [comment] 2024-04-13 18:23
I am going to renew this. I think I can try just grouping by stack in the UI. My prototype is looking nice.

**Comment by amir20** [comment] 2024-04-13 18:31
Here is a preview: 

<img width="215" alt="Screenshot 2024-04-13 at 11 30 36 AM" src="https://github.com/amir20/dozzle/assets/260667/33112a9c-c36e-498b-a3f6-e6193b13425b">

**Comment by amir20** [comment] 2024-04-13 20:36
PR at https://github.com/amir20/dozzle/pull/2893 

Someone give it a try with `amir20/dozzle:pr-2893`

**Comment by BaccanoMob** [comment] 2024-04-13 21:01
In you PR, you group by `com.docker.stack.namespace`, can you also add `com.docker.compose.project` as well?

When run `docker compose up -d`, the containers are grouped by `com.docker.compose.project` label for me.

Also I dont use docker swarm so I am not sure if there is difference in labelling due to that. (I think I got confused with portainer  stacks and docker stack/compose hence the title). Hope to see an update on this and thanks for looking into this issue!!

**Comment by amir20** [comment] 2024-04-13 21:05
> In you PR, you group by com.docker.stack.namespace, can you also add com.docker.compose.project as well?

That's a good idea! I don't use compose in production but I guess enough people do. I think `namespace` should take precedence though.

**Comment by amir20** [comment] 2024-04-13 21:08
OK pushed `com.docker.compose.project`. It should be up on docker hub in a few minutes. 

I wonder if the collapsing of the groups should be sticky? I don't want to make it too complicated. 

Any thoughts before releasing?

**Comment by BaccanoMob** [comment] 2024-04-13 21:46
Looks the way I wanted it to be. It would be nice if there is option in the settings for expanding or hiding the group by default as well as a collapse or expand all button in the side bar.

But grouping does not happen for mobile layout not sure if you missed it or not. Since I primarily check the logs full screen, it does not bother me much.

Sticky would be overkill in my opinion since I have like 3-5 in a compose file and making it sticky does make much difference in UI. Not sure for others. 

There is a very minor bug when you pin containers with some groups collapsed. The order of expanded groups change when a new group "pinned" goes on top.
Steps to reproduce:
- Collapse/Hide all groups.
- Expand the last group or a group with 2+ containers.
- Pin one container in it. 
- You see the group above automatically opens.
If you had some groups open and pin one container, its gets a bit unpredictable which stays expanded and which collapses.

**Comment by BaccanoMob** [comment] 2024-04-13 22:01
> But grouping does not happen for mobile layout not sure if you missed it or not. Since I primarily check the logs full screen, it does not bother me much.

Ignore this part, just realised when you click hamburger icon, it just lists the containers irrespective if its pinned or not. I think its should be okay to leave it as a list of container maybe? Not sure how it will look with collapsible groups.

**Comment by amir20** [comment] 2024-04-14 01:07
Yea, I generally do mobile later. It's a complete different flow so there is no point in trying to do both. 

It's a little inconsistent right now. I think the order is unpredictable and I think open and closing are not sticky. 

Still have work to do. 

Thanks for the feedback folks! It helps me so much to test it quickly.

**Comment by amir20** [comment] 2024-04-14 02:01
@BaccanoMob 

> There is a very minor bug when you pin containers with some groups collapsed. The order of expanded groups change when a new group "pinned" goes on top.


I am not able to reproduce this. Which browser are you testing? I am using Chrome. It seems to be working pretty well as is. I followed the directions and it is working. Can you maybe record a video? Also make sure you have the latest too.

**Comment by BaccanoMob** [comment] 2024-04-14 07:36
https://github.com/amir20/dozzle/assets/82655889/893ae34c-8263-4cf8-9223-160877ee4aa9

I use chrome too. I prolly did not word it correctly. Hope the video helps to what I am trying to say. 

After recording this for you, I think the best way to describe is the groups are expanded/collapsed based on the index of the list of groups rather than the group itself. 

Also I found when I was recording was that the order of list of group changes based on alphabetical order of the first container in the groups rather than the name of the group itself (According to the video, traefik group is after code-server because of dockerproxy is `D` but when I pinned dockerproxy, traefik groups goes to the last because of `T` of traefik container is after 'R').

Another thing, the stopped container are not visually distinct in the UI as before. 
![image](https://github.com/amir20/dozzle/assets/82655889/f6c4294d-d4a5-4f3a-8555-16414976af99)
![image](https://github.com/amir20/dozzle/assets/82655889/995e8a48-fabf-4dd4-95a4-516fc87d6fcb)
Maybe add green/red icon to denote the status? like when i use the search bar
![image](https://github.com/amir20/dozzle/assets/82655889/e4c36cf5-3230-4841-acad-ca0e9b041a2a)

Hope the feedback helps!

**Comment by amir20** [comment] 2024-04-14 16:05
Thanks. I was able to reproduce some of these. I think sadly I will have to some how implement some kind of stickyness. Sounds like browser uses the order to keep open.

**Comment by amir20** [comment] 2024-04-14 21:04
It should be all fixed now.

**Comment by amir20** [comment] 2024-04-14 21:06
Merged to master and will release soon.

**Comment by EDIflyer** [comment] 2024-04-14 23:05
Just noticed the change - is there going to be an option to hide stacks if you don't want them? It's just it has almost doubled the vertical height of things (I've very few items that have more than one docker service in the stack, but do you compose a lot to make it easier to manage things)...
New
![image](https://github.com/amir20/dozzle/assets/13610277/8bead2f7-01c9-4405-9f7e-df58f0e139f5)

Old (diff server so marginally different containers)
![image](https://github.com/amir20/dozzle/assets/13610277/35a0abc3-be7d-4e99-8d30-98b66a498081)

**Comment by amir20** [comment] 2024-04-15 00:12
I am working on that next. Was just waiting to bug me about it. 😉

**Comment by jordanlambrecht** [comment] 2024-04-15 20:25
@amir20 I don’t know if you already did this already, but make sure you remember to have it truncate the container name with ellipsis so it doesn’t run into the checkbox/edge if the user has long names!

**Comment by jordanlambrecht** [comment] 2024-04-15 20:37
@amir20 Also, indicator lights showing the last log message’s info/warn/error state would be cool if it’s not a heavy lift. Or is that a silly idea?

![IMG_0598](https://github.com/amir20/dozzle/assets/54866853/1dbacb08-c341-4bfa-8bce-2d5e0685f8e4)

**Comment by jordanlambrecht** [comment] 2024-04-15 20:39
> @amir20 Also, indicator lights showing the last log message’s info/warn/error state would be cool if it’s not a heavy lift. Or is that a silly idea?
> 

Oops I didn’t see @EDIflyer ‘s comment already suggesting that. Disregard.

**Comment by amir20** [comment] 2024-04-16 01:28
@jordanlambrecht that would be very hard since I would have to load each container logs and that would add a lot of CPU usage which most people don't want. 


@EDIflyer I have a question for you. Which one is more important: 

1. Completely disable stacks
2. Make the UI more compact? 

I am trying to do the least work and want to make sure if reducing the size is the goal then just do that.

**Comment by EDIflyer** [comment] 2024-04-16 06:40
@amir20 I was thinking probably just option to disable stacks altogether if that was the easiest? The other option would be to only show stacks where more than on container running within it?

**Comment by BaccanoMob** [comment] 2024-04-16 07:26
> @amir20 Make the UI more compact? 

> @EDIflyer other option would be to only show stacks where more than on container running within it?

If I need to look at the logs of a particular container, I would already know which stack it is at. Keeping the other stacks open in the sidebar is pointless (imo) when I open dozzle. So it should take couple of clicks to open the logs.

That's why I mentioned to use a toggle to collapse/expand all. Or just a setting to keep one by default.

Personally I would just hope you keep it closed by default without a setting to toggle. Since if we want to look at/list all the container we just need to click the dozzle logo in the corner anyway. No point in keeping all the groups expanded. This may make the UI more compact without needing to validate groups by checking if there's one or more container running in the stack.

**Comment by amir20** [comment] 2024-04-16 14:55
@EDIflyer @BaccanoMob Wouldn't both of your problems be solved if the expanded/collapsed groups were sticky between refreshes? 

For @EDIflyer it would only show the groups you want to so it would take less space.

For @BaccanoMob, you wouldn't need an expand or collapse all anymore. You would only manually collapse all groups once and from there on open just the ones you need. 

Right? 

I still plan to make the vertical space a little tighter. But disabling all groups will require to basically create a different version that might not get used often.

**Comment by amir20** [comment] 2024-04-16 15:02
> or only show if >1 container in a group?

I do like that idea. I am mostly trying to avoid yet another toggle in settings for something very few people will use.

**Comment by EDIflyer** [comment] 2024-04-16 18:32
Yep, sounds fair - I guess from my perspective (minimal stacks with >1 container) it just took me by surprise and seemed more cluttered, I can see the benefit for those with lots of containers per stack tho so hopefully this would be a useful compromise.

**Comment by BaccanoMob** [comment] 2024-04-16 18:40
(when you meant sticky I thought you meant with sticky headers when scrolling and was confused)

@amir20 Well if you want to avoid another toggle in the settings. Im okay with your solution being sticky between refreshes and i think its a good idea. Hope it gets merged with the next release!

@EDIflyer Well the work around is you can pin the single containers (only works when you don't pin typically though)

**Comment by EDIflyer** [comment] 2024-04-16 19:17
@BaccanoMob yeah I never bothered with pinning before but the current setup is causing a lot of duplication for my setup - hopefully the new tweak to only show if >1 container will do the trick!

![image](https://github.com/amir20/dozzle/assets/13610277/f7637fde-774c-46db-9612-b962874ab293)

**Comment by amir20** [comment] 2024-04-16 19:32
Give `amir20/dozzle:pr-2902` a try. It should do both sticky and only group when there is more than one container.

**Comment by BaccanoMob** [comment] 2024-04-16 19:46
Looks neat!

**Comment by EDIflyer** [comment] 2024-04-16 19:49
Thanks, @amir20 - looks much neater!

Perhaps 'All containers' should be renamed though to something like 'Single containers' (just as it isn't all containers, only those not displayed above).

![image](https://github.com/amir20/dozzle/assets/13610277/58c77ec7-ed2e-4c9f-9525-4ec9f1a13b2a)

**Comment by amir20** [comment] 2024-04-16 19:54
Its called all because you also showing stopped containers. Otherwise it would be `running containers`

**Comment by amir20** [comment] 2024-04-16 19:56
Ok releasing new build with this.

**Closed by amir20** 2024-04-16 19:56 UTC
Labels: enhancement

**Comment by EDIflyer** [comment] 2024-04-16 19:58
Yep tried switching off stopped and it changed to running - I guess I just found _all_ a bit misleading as it didn't include the ones above - I suppose they're not being counted as they're in stacks but it's just a bit of change from before.  Maybe just call it 'Containers' and don't bother showing running/all?

**Comment by amir20** [comment] 2024-04-16 20:07
Fair point. Will think about all these later.

**Comment by BaccanoMob** [comment] 2024-04-16 20:13
maybe `Other Containers` would be good heading perhaps?

**Comment by amir20** [comment] 2024-05-02 16:54
No plans right now to add an ENV. Perhaps if more people need it. @JenangMaker PRs are welcomed though.
