### ISSUE TITLE
GPU Metrics

### ISSUE THREAD

**Issue by mbbyn** [amir20/dozzle#2481] opened 2023-11-08 06:10 UTC
Hello,
We've been using dozzle for a while now, and it's been evolving very nicely over the years. If we had one nitpick it would be GPU metrics monitoring. As per our current setup, it's not trivial to monitor the GPU utilization unless we drop to the cli level.

It would be phenomenal if we could see the GPU VRAM utilization, and if possible, the compute/CUDA utilization as well. This is becoming more and more important as the GPU becomes an integral part of most setups with the advent of LLMs.

Thanks,

**Comment by mbbyn** [comment] 2023-11-09 10:55
Thanks a lot for looking into it, @amir20. I sympathize with your approach of running dozzle as lean as possible. I just noticed it's built `FROM scratch`, without shell access even. The approach we use is `nvidia-smi` which automatically gets added to the containers with `--gpus all` flag + `nvidia-container-toolkit`. This requires heavy lifting and might not fit the goals of the project.

However, I can't help but think about a "raw" hardware access and checking that is vendor agnostic. I will try to see if there is such a thing.

**Comment by amir20** [comment] 2023-11-09 20:05
Thanks for pointing me to `nvidia-smi`.  It did help me find some scripts like https://github.com/nawafalageel/docker_container_gpu_exporter that could collect such data. The problem is that this data is not streamed so Dozzle would have to do that work. I also don't know if mounting the `nvidia-smi` binary would just work. 

I got some exploring to do. 

> sympathize with your approach of running dozzle as lean as possible

Yes, I try to minimize it. My overall principle has been that Dozzle should be lean for majority of users. Both from UI perspective but also from disk usage and CPU. So for this, I was thinking maybe there could be a companion Dozzle service that collects GPU stats like `amir20/dozzle-gpu-collector` that would figure out the core logic and expose a simple http stream to Dozzle. Since this container is optional, it could be a little fatter. 

For this work, it would be awesome if you had some examples of how one could fetch this data _inside_ a container. I have no idea if it will work, I also don't really have a test machine with nvidia. So it will take a little testing.

**Comment by amir20** [comment] 2023-11-10 22:51
>  I have no idea if it will work, I also don't really have a test machine with nvidia. So it will take a little testing.

I tried figuring this out. I don't have any Nvidia machines and couldn't find an easy way to test in the cloud. @mbbyn is there a method to test this without having a test machine?

**Comment by mbbyn** [comment] 2023-11-14 10:40
@amir20 sorry for the delay. Unfortunately, I am not aware of an approach to test it without access to an Nvidia hardware. I'm happy to help with testing on my side if that helps.

> For this work, it would be awesome if you had some examples of how one could fetch this data inside a container. I have no idea if it will work, I also don't really have a test machine with nvidia. So it will take a little testing.

I tested this, and found that if I run a container as root with `--privileged` flag, and run `nvidia-smi` command, I get the full details of the GPU, including the running processes. The interesting part is that the container can be almost any container, not necessarily the `nvidia` images that they publish. For example, notice how I use a bare `debian` image without additional CUDA libraries in the container itself. However, when testing this with `alpine` images, sadly it didn't work.

```
docker run --rm -it --entrypoint sh --gpus all -u root --privileged -e NVIDIA_VISIBLE_DEVICES=all debian:12.2
# nvidia-smi
Tue Nov 14 10:37:45 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.14   Driver Version: 528.86       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 6000     On   | 00000000:65:00.0  On |                  Off |
| 34%   36C    P8    25W / 260W |   3115MiB / 24576MiB |      6%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       107      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+
```

**Comment by amir20** [comment] 2023-11-20 17:45
@mbbyn I don't think I can work on this. I did some googling and AWS is the only provider that has GPU/NVDIA options. But it is at $0.379/hour which means a few hundred dollars for me to just build and test. 

If any body on your side would be able to provide a service that Dozzle could use then I could work with you to integrate it. But for now, it seems like it is out of my scope. I do think it's a great idea though! 

If you find any other cloud options that are cheap please do let me know.

**Comment by amir20** [comment] 2023-12-13 19:50
Going to close this since I still haven't found a way to implement it without nvidia hardware.

**Closed** 2023-12-13 19:50 UTC
Labels: enhancement
