### ISSUE TITLE
SSL Recommended but how?

### ISSUE THREAD

**Issue by LostOnTheLine** [amir20/dozzle#1991] opened 2022-12-18 05:55 UTC
**Is your feature request related to a problem? Please describe.**
The Instructions say
```
Authentication
Dozzle supports a very simple authentication out of the box with just username and password. You should deploy using SSL to keep the credentials safe.
```
But then there is nowhere where the details on how to enable the SSL certificates. I've added it to NGINX & it doesn't work, I looked through all the documents I could find but I don't see anything

**Describe the solution you'd like**
Add details for the ENV vars or or SSL mapping location needed to use SSL & HTTPS.

**Describe alternatives you've considered**
As of now it's usable, but seriously limited. It's mentioned, so the container must support it

**Additional context**
A few other ENV flags are mentioned here & there that are also not in the docs, like `DOZZLE_TAILSIZE=100` & there's not really any explanation about `healthcheck:` except an example of how it's used in a compose, that's also be useful.

**Comment by amir20** [comment] 2022-12-18 13:48
Dozzle doesn't support SSL. You have to use NGINX or some other proxy to enable SSL. 

Personally, I use traefik. But that's up to you.

**Comment by amir20** [comment] 2022-12-18 14:55
Also tailsize was removed. I'll update the readme file.

**Comment by amir20** [comment] 2022-12-18 22:43
@LostOnTheLine there is no `DOZZLE_TAILSIZE=100` in the readme file. I am not sure where you see that.

**Comment by amir20** [comment] 2022-12-18 22:44
Closing this because supporting SSL is out of scope right now. Maybe in the future if more people need it then I can consider it.

**Closed** 2022-12-18 22:45 UTC
Labels: enhancement

**Comment by LostOnTheLine** [comment] 2022-12-20 13:04
> @LostOnTheLine there is no `DOZZLE_TAILSIZE=100` in the readme file. I am not sure where you see that.

I'm not sure where I saw it, but I was looking through things trying to find how to do the SSL & I saw it multiple places. Tailsize **_is_** listed on [Dockerhub](https://hub.docker.com/r/amir20/dozzle/), though without details, if it's no longer supported it should be removed from there as well.

<html>
<body>
<h4 style="box-sizing: inherit; margin-bottom: 1em; margin-top: 1em; overflow-wrap: break-word; color: rgb(57, 63, 73); font-family: Roboto, system-ui, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Environment variables and configuration</h4><p style="box-sizing: inherit; margin-bottom: 1em; margin-top: 1em; overflow-wrap: break-word; line-height: 1.75; color: rgb(57, 63, 73); font-family: Roboto, system-ui, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Dozzle follows the<span> </span><a href="https://12factor.net/" style="box-sizing: inherit; color: rgb(15, 108, 158); background-color: transparent; overflow-wrap: break-word; text-decoration: none;">12-factor</a><span> </span>model. Configurations can use the CLI flags or environment variables. The table below outlines all supported options and their respective env vars.</p>

Flag | Env Variable | Default
-- | -- | --
--addr | DOZZLE_ADDR | :8080
--base | DOZZLE_BASE | /
--level | DOZZLE_LEVEL | info
n/a | DOCKER_API_VERSION | not set
<b>--tailSize</b> | <b>DOZZLE_TAILSIZE</b> | <b>300</b>
--filter | DOZZLE_FILTER | ""
--username | DOZZLE_USERNAME | ""
--password | DOZZLE_PASSWORD | ""
--key | DOZZLE_KEY | ""
--no-analytics | DOZZLE_NO_ANALYTICS | false

<p style="box-sizing: inherit; margin-bottom: 1em; margin-top: 1em; overflow-wrap: break-word; line-height: 1.75; color: rgb(57, 63, 73); font-family: Roboto, system-ui, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Note: When using username and password<span> </span><code style="box-sizing: inherit; font-family: &quot;Roboto Mono&quot;, consolas, monaco, monospace; font-size: 0.95em; overflow-wrap: break-word; padding: 0.1em 0.4em; background-color: rgb(245, 245, 245); border-radius: 1px;">DOZZLE_KEY</code><span> </span>is required for session management.</p>
</body>
</html>

---
The problem with NGINX is that it requires it to be publicly accessible, which is exactly what I don't want. But even then, setting it up via NGINX, which I already use, returns a `502 Bad Gateway` error. In the readme you state that SSL should be used, `"Dozzle supports a very simple authentication out of the box with just username and password. You should deploy using SSL to keep the credentials safe."` but as far as I can tell it can't be. I could map a folder with an SSL certificate (either Self-signed or reverse proxy) but I don't know where to map it to for it to be used. 

Personally I'm trying to have Dozzle as an iframe in Home Assistant, which requires an SSL certificate if home assistant uses one, so anyone who has Home Assistant exposed to the internet. SSL has been the standard for at least 10 years, just saying. But it's rare to find Containers that don't support it, even if they don't use it by default. [crontab_UI](https://github.com/alseambusher/crontab-ui) has a very basic approach that seems pretty simple, they just have ENV variables that you can set to point to SSL certificates if you choose to use them `SSL_CERT=` & `SSL_KEY=` so I can mount my cert folder to `/certs` & then set those to `SSL_CERT=/certs/cert.pem` & `SSL_KEY=/certs/key.pem` I'm not sure how much work that requires from a developer viewpoint, but I imagine it isn't much.
But if you aren't going to support it, that's fine, it's your app, but you should remove the recommendation to use an SSL certificate from the readme & instead say `"Dozzle supports a very simple authentication out of the box with just username and password. We don't currently support SSL as it isn't intended to be used out of a secure environment."`  & maybe give a warning that the username & password will not be very secure.

**Comment by amir20** [comment] 2022-12-20 15:11
You can send a PR to support SSL. I won't have time to support or answer questions about it. 

I have not heard anybody else struggle with SSL and nginx. I know it works and you can set it up to none public. An application should never implement SSL as it can be delegated to the reverse proxy. 

If the 502 error is Dozzle's bug then let me know how it can be reproduced.
