### ISSUE TITLE
Load Chart Visulation

### ISSUE THREAD

**Issue by RefineryX** [amir20/dozzle#2215] opened 2023-05-24 15:38 UTC
I wanted to check what the expected behaviour for the load graph is?

It appears to be working on some containers but not all.

I think the expected behaviour is like the below image, which visualises various spikes etc.

<img width="172" alt="Screenshot 2023-05-24 at 16 33 06" src="https://github.com/amir20/dozzle/assets/46373533/f4552d42-c8db-43cf-8829-0ba784ff5df9">

However, on some containers I get a constant flat line.

<img width="165" alt="Screenshot 2023-05-24 at 16 33 23" src="https://github.com/amir20/dozzle/assets/46373533/ab0ba3a6-2d74-4d74-9b0d-4e1f51667bc2">

**Comment by amir20** [comment] 2023-05-24 16:58
Thanks for the question @RefineryX! You are right this could be confusing.

Stats are collected when you first load Dozzle in the browser. After 5 minutes, it will become a rolling window of past 5 minutes. 

When the CPU usage is 0 for a period of time, you will see a flat line. The reason it is in the middle is because all the data points are 0 which results in a just flat line. Since max and min are also 0, the line is drawn in the middle of the chart. 

So it should be working as intended because your CPU is not moving much.

**Comment by amir20** [comment] 2023-05-26 17:58
Didn't hear back.Closing

**Comment by RefineryX** [comment] 2023-05-26 18:30
> Thanks for the question @RefineryX! You are right this could be confusing.
> 
> Stats are collected when you first load Dozzle in the browser. After 5 minutes, it will become a rolling window of past 5 minutes.
> 
> When the CPU usage is 0 for a period of time, you will see a flat line. The reason it is in the middle is because all the data points are 0 which results in a just flat line. Since max and min are also 0, the line is drawn in the middle of the chart.
> 
> So it should be working as intended because your CPU is not moving much.

Thanks. Would it make more sense to eliminate the line? I now get the reason why it’s drawn in the middle in such a way but taking a step back, the line represents activity and it can cause confusion especially when there has been zero activity. I would rather see nothing rather the current behaviour.

**Comment by amir20** [comment] 2023-05-26 18:36
By remove, do you mean make the line not in the middle but more accurately at the base of the graph? I had a PR for this but I don't think I ever did it.

**Comment by RefineryX** [comment] 2023-05-26 18:41
Before reading your initial response, I initially thought the activity was sitting at a constant ~50% or it was broken. 

I think that would also work and better reflect the true activity.

**Comment by amir20** [comment] 2023-05-26 19:01
Ok I found the fix. Going to release. I think it should work. I didn't test it a lot 🚀

**Closed** 2023-05-26 19:07 UTC

**Comment by RefineryX** [comment] 2023-05-26 19:24
Excellent! Just updated now and so far, so good. Will let you know if there are any issues.

Thanks for being so responsive!
