### ISSUE TITLE
docker beta pull

### ISSUE THREAD

**Issue by adamaen87** [amir20/dozzle#2389] opened 2023-09-23 09:48 UTC
Hello,

first, thank you for this great software.
It is installed with docker and i use diun to receive update notifications.
I use the "latest" tag to pull image and today i received the version5.0.0-beta0 instead of the last version 4.11.5?
Is this an expected behaviour?

Thanks,

**Comment by adamaen87** [comment] 2023-09-23 09:49
This is my compose:
`version: "3.5"

networks:
  dozzle:
    name: dozzle

services:
  dozzle:
    container_name: dozzle
    environment:
      DOZZLE_NO_ANALYTICS: true
    hostname: dozzle
    image: amir20/dozzle:latest
    networks:
      - dozzle
    ports:
      - 9999:8080
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro`

**Comment by agneevX** [comment] 2023-09-23 12:27
I can confirm this issue exists. This is why it's best to use version pinning.

**Comment by amir20** [comment] 2023-09-23 14:11
@agneevX Since you are a regular user can you tell me if beta looks good? It was only UI changes so I don't expect any bugs.

**Comment by agneevX** [comment] 2023-09-23 16:27
@amir20 thanks for asking... overall it looks quite nice but I think the sidebar padding could be reduced a bit, the container font size decrease hurts a little.

<img width="208" alt="new" src="https://github.com/amir20/dozzle/assets/19761269/111fbc7c-1a03-423d-86ae-9cdbe1a285c7">

<img width="212" alt="old" src="https://github.com/amir20/dozzle/assets/19761269/4e9548f6-1c89-4a10-b8de-a8e1065b5af3">

Another thing I noticed is that the timestamp lacks a space:

<img width="185" alt="Screenshot" src="https://github.com/amir20/dozzle/assets/19761269/cfc363c6-474d-4b85-84cc-f1a8d167c126">

Unrelated but adding a home button (beside settings icon maybe?) would make it better than clicking on the logo to go home.

Finally, clicking on any sort button sorts it in ascending order, can this be changed to desc for Created, Avg. CPU and Avg. Mem?

**Comment by amir20** [comment] 2023-09-23 20:07
Thanks @agneevX !

I'll see if I can fix the padding. 

You are right about the timestamp. I just fixed that. 

Clicking the column should switch from ascending to descending. Or are you saying the first click should be descending?

**Comment by amir20** [comment] 2023-09-23 20:24
OK fixed the padding a little. 

I'll come back to home button and sort after a release.

**Comment by amir20** [comment] 2023-09-23 20:34
OK closing this. Released v5 now.

**Closed by amir20** 2023-09-23 20:34 UTC

**Comment by agneevX** [comment] 2023-09-24 04:31
Thank you @amir20. Changes look very good!

> Clicking the column should switch from ascending to descending. Or are you saying the first click should be descending?

Columns like `container name` might need to be asc since people may expect it like that. But for `avg CPU` or `avg MEM`, desc might make sense because you might want to figure out what is using the most CPU or memory.

**Comment by amir20** [comment] 2023-09-24 14:29
Hey @agneevX I am still not understanding. The sort changes when clicked again. Are you saying that's not working?
