### ISSUE TITLE
RangeError: Invalid time value when new log appear

### ISSUE THREAD

**Issue by bonny1992** [amir20/dozzle#273] opened 2020-02-07 22:31 UTC
Hey, it's me, again 🗡 

After having you help me a lot [here](https://github.com/amir20/dozzle/issues/271), I encountered another error.

As before, if this is only reproduceable on my particular environment and/or it is too much to fix (if there is anything to fix).

Now, when the logs are fully loaded after clicking on them, if a new line of the log appear, instead of adding it to the bottom it only goes with `RangeError: Invalid time value` in the console.

If I click on another container, then again in the same as before, of course it updates the entire thing.

**Comment by amir20** [comment] 2020-02-07 22:43
This might be a bug I had seen before. I am curious, are you using `tty:true`? When is tty is true, I have no idea how long a message is so I read until end of line. When tty is false, each line is prepended by length, so I can read that whole line first. Which means, when there are line breaks, it might break when tty is true because I don't know how far too read.

**Comment by bonny1992** [comment] 2020-02-07 23:08
Do you mean if I run Dozzle with tty or the containers I'm trying to read their logs?

Because this is one of my usual `docker run` command.

```
docker run -d --name minio \
    -e MINIO_ACCESS_KEY=foo \
    -e MINIO_SECRET_KEY=foo \
    --user $(id -u):$(id -g) \
    -v /volume1/Storage/s3:/data \
    -p 9999:9000 \
minio/minio \
 server /data
```
and this breaks the auto-refresh.

Am I right to think that "no flag" means "flag = false" in this particular case?

**Comment by amir20** [comment] 2020-02-07 23:49
I mean the container you are trying to run. 

It doesn't look like you are using tty. It is the `-t` option. 

Hmm soooo then I don't know what it can be. 

What is the log line that is breaking? Any way I can reproduce it?

**Comment by bonny1992** [comment] 2020-02-08 11:28
I don't really know how you can reproduce it because it gives that error every time a new log line is received by Dozzle (when it should update the page).

Is there any way to enable a more verbose trace (more than `--level=trace`) from Dozzle? Maybe I can see what it receives and tries to send.

**Comment by amir20** [comment] 2020-02-08 17:40
@bonny1992 I think I misunderstood the magnitude of this issue. I thought you said for only _some_ logs it would throw that error. 

Did you mean that it throws that error for _every_ single new log message that comes through?

Just for my entertainment, can you try dozzle on a different host with more recent version of Docker installed? I want to make sure there is something else going on that we don't know about. If it works, then most likely the culprit is Docker 1.18 .

**Comment by bonny1992** [comment] 2020-02-09 00:12
Sure I'll try it right now.

I'll edit the message as I get the results.

**Comment by amir20** [comment] 2020-02-09 20:52
Thanks for the update @bonny1992. Good thing I checked because Github doesn't send emails for edits. 

It's great news that later versions are not broken. I was worried that there was something wrong with the container your were testing, but it seems like Dozzle works fine.  I usually test with latest so that was to be expected. 

Regarding the specific version, then that's surprising. The fact that Docker 1.18 works on Debian, that's also good news.  I am going to guess that there was some patch fix for this but DSM never updated. Bummer...
 
> Dozzle starts a socket connection when it sees the container starting

Yep. Dozzle uses [HTTP event streams](https://www.html5rocks.com/en/tutorials/eventsource/basics/).  When server is shutdown, then all streams are also disconnected which is why you get that error. 

Alright so now for the problem that you are having. :) 

I could `try-catch` all date parsing errors and use `Date.now` instead. But I feel like that would be hacky. Because it would hide all kind of other errors which are probably not great for debugging. And since it is not specific to the Docker version, then I can't do `if VERSION == '1.18'` do something else. 

Not sure what to do here :P Maybe invest in a newer Synology 🤷🏻‍♂️

**Comment by bonny1992** [comment] 2020-02-09 21:34
Yeah, no worries about that, I understand that this issue is regarding me and only me (probabily) so there is no need to invest time and resources to fix this, since no one else is gonna be affected.

If I knew how to code in Go I'd fix that myself :P haha

> Not sure what to do here :P Maybe invest in a newer Synology 🤷🏻‍♂️

Yeah, I know :( haha

**Comment by amir20** [comment] 2020-02-10 00:20
Sounds good. Then I'll close.

**Closed by amir20** 2020-02-10 00:20 UTC
Labels: invalid, question
