### ISSUE TITLE
Horizontal Scroll bar not coming

### ISSUE THREAD

**Issue by vishnuidp** [amir20/dozzle#75] opened 2019-07-15 12:52 UTC
Hi,

Horizontal scroll bar not coming, when message length is too big, its getting truncated from right

**Comment by amir20** [comment] 2019-07-15 16:59
Do you have a screenshot? All my messages are wrapped so I don't think this should happen.

**Comment by vishnuidp** [comment] 2019-07-15 17:14
yesah, attached the same... its not getting wrapped for me. !
![dozzle](https://user-images.githubusercontent.com/38692498/61234940-f5d3d180-a751-11e9-93e4-86ca25a8e0cb.JPG)

**Comment by amir20** [comment] 2019-07-15 18:11
What version are you running? That looks to be old. If you see the screenshot I attached, you can see that everything is wrapped. 

<img width="1640" alt="Screen Shot 2019-07-15 at 11 10 55 AM" src="https://user-images.githubusercontent.com/260667/61238342-4c5cf380-a6f1-11e9-91ae-a176dcc8e7e5.png">

Latest version is `1.11.6`

**Comment by kigero** [comment] 2019-07-15 20:41
I'm having a similar issue - it does look like it's wrapping at some point, but it's definitely not wrapping everything, and not bringing up a horizontal scroll bar.  In the screenshot you can see that the json is wrapping, but it's not wrapping at the boundary but somewhere past it.  The last two lines aren't wrapping at all.

![image](https://user-images.githubusercontent.com/679688/61246903-f6527500-a71d-11e9-8612-1896a6e1afb4.png)

Just from a really quick look at the page in Chrome it looks like the width of the div that contains all of the line data is a lot wider than the actual viewable width - I'm not sure where that width is coming from, but if I constrain it to be the visible width the wrapping appears to happen properly.

**Comment by vishnuidp** [comment] 2019-07-15 20:45
I am using latest version. Like @kigero mentioned, for me also, its wrapping some logs, but its not wrapping all the logs.

**Comment by vishnuidp** [comment] 2019-07-15 20:48
And even the places its wrapping, its not very clear as User perspective, a horizontal bar would be really great. Thanks in advance. :)

**Comment by amir20** [comment] 2019-07-15 21:37
I am trying to figure out if the right solution would be to add horizontal bar or understand why it's not wrapping always correctly and fix that instead?

**Comment by amir20** [comment] 2019-07-15 21:43
Ah I was able to reproduce this by making my screen smaller. Let me see if I can fix this without adding a scrollbar first.

**Comment by amir20** [comment] 2019-07-15 22:51
This might be fixed in https://github.com/amir20/dozzle/commit/c04535d9b07a831d7abc2f91f961a31c73b5b5ca. Thanks for filing it @vishnuidp and @kigero. 

Can you try `v1.11.8` please? I ended fixing the width so no scroll bar should be needed.

**Comment by kigero** [comment] 2019-07-15 23:48
That seems to have done it - wrapping looks much nicer now.  Thanks!

![image](https://user-images.githubusercontent.com/679688/61256109-75a17200-a739-11e9-8ee1-2608b0ca6dd0.png)

**Closed** 2019-07-15 23:56 UTC
Labels: bug
