### ISSUE TITLE
Sometimes a strange timestamp may appear

### ISSUE THREAD

**Issue by devioa** [amir20/dozzle#2431] opened 2023-10-20 06:03 UTC
![动画](https://github.com/amir20/dozzle/assets/38558065/08e64c59-890d-49b2-be11-51e9689b247d)
It may appear in any of my container logs, and this GIF animation only demonstrates the situation in container `AdGuardHome` because it is very easy to reproduce here.

**Comment by devioa** [comment] 2023-10-20 09:22
![image](https://github.com/amir20/dozzle/assets/38558065/fe42e859-65e6-4da8-b795-03040e215bb7)
I just found a different one

**Comment by amir20** [comment] 2023-10-20 16:54
First, I never knew about AdGuardHome. I have been using PiHole. Will have to give that a try. 

Back to the issue, something weird is going on. Even the timestamps are not parsed correctly. 

Couple of questions: 

1. Are you running in interactive mode, using `-i` for the container? 
2. Does this only happen to AdGuardHome? Or other containers too.


I'll test AdGuardHome locally and let you know what I find.

**Comment by devioa** [comment] 2023-10-20 17:05
1. no, I using `Portainer`'s Stacks to deployed containers
> It may appear in any of my container logs, and this GIF animation only demonstrates the situation in container `AdGuardHome` because it is very easy to reproduce here.

2. It may happen any of my containers. The situation in my second comment was found in other container

**Comment by devioa** [comment] 2023-10-20 17:08
![image](https://github.com/amir20/dozzle/assets/38558065/5ce77559-5e91-411e-a876-98333f137b62)

**Comment by amir20** [comment] 2023-10-20 17:12
Hmm just tested AdGuardHome and no problems yet. I'll have to keep testing. 

Seems like you are running latest version of Dozzle? Is that right? 

Most likely something is happening when the bytes are being transferred from Docker to Dozzle API. But I can't really fix it if I can't reproduce it.

**Comment by devioa** [comment] 2023-10-20 17:21
> Hmm just tested AdGuardHome and no problems yet. I'll have to keep testing.

Yes, I cannot reproduce this issue 100% because sometimes it disappears when switching to another container and then switching back, as demonstrated in my GIF animation. However, now I try to reproduce it in AdGuardHome but I couldn't reproduce it anymore.
> Seems like you are running latest version of Dozzle? Is that right?

Yes, I am currently using Dozzle with built from latest source code.

> Most likely something is happening when the bytes are being transferred from Docker to Dozzle API. But I can't really fix it if I can't reproduce it.

So I said it's "strange".

**Comment by devioa** [comment] 2023-10-20 17:25
Could it be due to the last fix #2416? Because I have never observed such a problem before.

**Comment by amir20** [comment] 2023-10-20 17:43
> Could it be due to the last fix https://github.com/amir20/dozzle/issues/2416? Because I have never observed such a problem before.

It could be. The problem with that fix was when a bad byte was found I was ending the connection. So maybe I am actually returning the bad byte now. 

Good idea. Let me check the code closer.

**Comment by devioa** [comment] 2023-10-20 17:49
well, wish you good luck!

**Comment by amir20** [comment] 2023-10-20 18:00
You were right. That is the cause. But now I don't know what to do. 

I have an error called `ErrBadHeader` which happens when I can't part the logs. There could be many reasons why this could happen. 

Should Dozzle skip those lines? Or do something else?

**Comment by amir20** [comment] 2023-10-20 18:21
<img width="984" alt="Screenshot 2023-10-20 at 11 21 18 AM" src="https://github.com/amir20/dozzle/assets/260667/9de2305f-a117-4e54-9ed2-f4b85a6e3837">

I was able to reproduce this now. I just have to figure out what to do about it now. :)

**Comment by amir20** [comment] 2023-10-20 18:46
I am idiot. 🥇 I wasn't reading the buffer correctly. I think I'll have a fix soon. haha. Thanks for filing this bug!

**Comment by amir20** [comment] 2023-10-20 18:58
Test `5.0.9`.

**Comment by amir20** [comment] 2023-10-20 19:59
Should be fixed now. Added bonus, I fixed the log levels for `adguard/adguardhome` so info shows correctly. 

<img width="853" alt="Screenshot 2023-10-20 at 12 58 23 PM" src="https://github.com/amir20/dozzle/assets/260667/91e404f0-5cd0-4570-b306-1db903eebcc5">

**Closed by amir20** 2023-10-20 19:59 UTC

**Comment by devioa** [comment] 2023-10-21 01:33
well done!!!👍
