### ISSUE TITLE
Docker Swarm: only containers from the node that Dozzle is running on are shown.

### ISSUE THREAD

**Issue by darkl0rd** [amir20/dozzle#496] opened 2020-05-31 09:25 UTC
When deploying Dozzle on Swarm, the containers shown are those running on the respective (manager) node. Containers from other nodes in the swarm are not listed.

The documentation seems to (indirectly) imply that this should be the case though, as it is suggested to constrain the deployment to a manager node.

So currently this seems to behave like "docker logs" rather than "docker service logs".
Would you please be willing to enhance its functionality to be able to stream logs from all containers residing in a swarm?

Thanks :)

**Comment by amir20** [comment] 2020-05-31 18:15
Hi @darkl0rd, I also use swarm and have been wanting to do this. You are right that the README makes it sound like it works in Swarm. Someone had added that to README file as a PR and I didn't think much of it. 

This issue is actually a duplicate of https://github.com/amir20/dozzle/issues/297. I looked into this a while back and there is a serious issue with `docker service logs ...` where the output is randomized. You can follow the issue at https://github.com/moby/moby/issues/33183. I have been following it for the last year and it doesn't look like it has been fixed yet. 

I think having a broken experience with Dozzle in Swarm mode is not ideal and would result in a lot of people opening unrelated bugs. 

So yes, I would love to add this feature. I'll take any help I can if you want to do further investigation. For now, it seems like there is an upstream issue that is blocking this issue.

**Comment by amir20** [comment] 2020-06-06 14:53
I just did `docker service logs ...` for one of my own docker stacks and the order still seems broken. So going to close until there is an update on the bug from docker. If you want to help out, you can try to investigate as well.

**Closed by amir20** 2020-06-06 14:53 UTC
Labels: duplicate, enhancement, help wanted, question

**Comment by Hakujou** [comment] 2020-08-05 00:15
You can get individual containers logs on Swarm using:
docker service ps xxx
docker service logs <id>

where <id> is one of the instance returned by ps. I used it for years, it works perfectly, including on other nodes logs (at least on CentOS). 

Isn't that enough ? I think Portainer uses pretty much this, and it works fine.

**Comment by amir20** [comment] 2020-08-05 02:21
🤔 https://github.com/portainer/portainer/blob/cf5056d9c03b62d91a25c3b9127caac838695f98/app/docker/rest/service.js 

It doesn’t sound like that is what Portainer does. 

However, your idea sounds interesting. I won’t have time to test it out anytime soon. But it does sound like an overkill to watch all containers of a service. At least it’s a decent option to watch logs. I wonder if it will work on a large cluster though.

**Comment by darkl0rd** [comment] 2020-08-05 07:34
I always use this too in large clusters (100+ nodes, 2500+ services). It works well in general. There is one bug with it, that is that under certain circumstances it can happen that the logs no longer stream. When this happens you need to forcefully rotate the ca. Other than that it works like a charm.

**Comment by Hakujou** [comment] 2020-08-05 09:35
> I always use this too in large clusters (100+ nodes, 2500+ services). It works well in general. There is one bug with it, that is that under certain circumstances it can happen that the logs no longer stream. When this happens you need to forcefully rotate the ca. Other than that it works like a charm.

I use it on a non-encrypted Swarm, so that could explain it.
