### ISSUE TITLE
Attach Dozzle Agents when operating in Swarm Mode

### ISSUE THREAD

**Issue by meerumschlungen** [amir20/dozzle#3378] opened 2024-11-10 20:26 UTC
### Describe the feature you would like to see

Thank you for your outstanding work!
I use Dozzle on a Docker Swarm consisting of three manager nodes.
However I run two separate Docker hosts standalone which have special hardware and are not part of the swarm. I tried to run dozzle agents on the standalone hosts and attach them to my main dozzle service running in the swarm. As far as I can see from the code, this use case is not covered, the agents provided in the arguments are not evaluated at all when operating in swarm mode.

### Describe how you would like to see this feature implemented

It would be cool to have all container related logs under one single UI. As far as I can tell, from the UI perspective, everything should be there. When the backend would consider the provided agents, they could appear as separate nodes alongside the swarm itself and it wouldn't be necessary to run multiple server instances across different URLs.

**Comment by amir20** [comment] 2024-11-10 21:51
> However I run two separate Docker hosts standalone which have special hardware and are not part of the swarm. I tried to run dozzle agents on the standalone hosts and attach them to my main dozzle service running in the swarm.

Wow you might be the first person to use Dozzle with such an advanced configuration. 

> As far as I can see from the code, this use case is not covered, the agents provided in the arguments are not evaluated at all when operating in swarm mode.

That is right! Swarm uses `SwarmClientManager` which only reconnects to other swarm nodes. 

> they could appear as separate nodes alongside the swarm itself and it wouldn't be necessary to run multiple server instances across different URLs.

As far as I can tell, this should be doable. The code would need to be changed to also allow for "other" agents. However, there might be performance considerations because all nodes in the swarm would need to connect to the agents.  The UI should just work without any changes. I suspect all the changes would need to be on the backend. 

I'll give it a try next week when I have some time to see if anything breaks. Since you already looked at the code, you can try to see if you can add this feature by adding it `NewSwarmClientManager` function in `swarm_client_manager.go`.

**Comment by mitchplze** [comment] 2024-11-15 11:11
Hello. I've just come searching for this exact same issue, and was planning to raise it if it wasn't here! 

Docker Swarm seems to be getting more traction lately. I also have the exact same situation as OP, where I have a lovely Swarm cluster, but also a bunch of independent nodes. Some of these are even spread around the world, but with VPN I can monitor them all at once - very slick.

Unfortunately since implementing Swarm mode in Dozzle, I have to run two separate Dozzle instances now: one for the Swarm, and one with `DOZZLE_REMOTE_AGENT={{hosts}}`. 

It would be absolutely awesome to bring remote agent support into Swarm mode!

Thanks for an amazing project @amir20. I use Dozzle more than almost anything else for my container monitoring.

**Comment by amir20** [comment] 2024-11-15 15:44
I haven't had a chance to work on this yet. Hopefully, soon. 

> Docker Swarm seems to be getting more traction lately

Is this true? I hadn't seen much about it. 

I'll let you know when there is something to test.

**Comment by mitchplze** [comment] 2024-11-15 19:06
I’ve noticed it popping up a lot more lately. Lots of people (myself included) confused Swarm mode with the older unsupported mode of the same name.

Once I learned Swarm was a first class feature, I couldn’t wait to get a cluster going! It’s been rock solid so far with NFS-backed volumes in the compose.

**Comment by mitchplze** [comment] 2024-11-15 20:04
> @mitchplze can you try and report back? It might be something with my network.

@amir20: Thanks for the quick work! Unfortunately does not work for me. I'm not getting any errors related to my remote agents at all. It doesn't appear to be trying them. 

In my network, VCD1, 2, and 3 are the Swarm members. I'm trying to access another remote box called HS1 running Dozzle and the Docker Proxy container. 

compose.yml
````
---
        
services:
  dozzle:
    # image: amir20/dozzle:latest
    image: amir20/dozzle:pr-3394
    environment:
      - DOZZLE_LEVEL=debug
      - DOZZLE_MODE=swarm
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_ENABLE_ACTIONS=true 
      - DOZZLE_REMOTE_HOST=tcp://100.121.168.112:2375|hs1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    ports:
      - "9999:8080"
    networks:
      - dozzle
    deploy:
      mode: global
      # mode: replicated
      # replicas: 1

networks:
  dozzle:
    driver: overlay

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.5.5,nolock,soft,rw
      device: :/volume1/docker/dozzle/data    
````

When I launch the stack, all three Dozzle nodes come up. _None of them has anything related to the remote host._ 

Log outputs below. 

vcd1
````
2024-11-15T19:55:07Z INF Dozzle version pr-3394 
2024-11-15T19:55:07Z DBG Creating local client | filterArgs={}
2024-11-15T19:55:07Z DBG Fetching host | host=vcd1
2024-11-15T19:55:07Z DBG Finding container | id=32fd1b920176
2024-11-15T19:55:07Z DBG Listing containers | filter={} host=vcd1
2024-11-15T19:55:07Z DBG Fetching host | host=vcd1
2024-11-15T19:55:07Z DBG docker store subscribing docker events | host=vcd1
2024-11-15T19:55:07Z DBG found swarm service name | service=dozzle_dozzle
2024-11-15T19:55:07Z INF Starting in swarm mode 
2024-11-15T19:55:07Z DBG Using simple authentication 
2024-11-15T19:55:07Z DBG Fetching host | host=vcd1
2024-11-15T19:55:07Z DBG Listing containers | filter={} host=vcd1
2024-11-15T19:55:07Z INF Dozzle agent version pr-3394 
2024-11-15T19:55:07Z DBG Fetching host | host=vcd1
2024-11-15T19:55:07Z DBG docker store subscribing docker events | host=vcd1
2024-11-15T19:55:07Z DBG Reading users.yml file | path=/data/users.yml
2024-11-15T19:55:07Z DBG Loaded users | users=1
2024-11-15T19:55:07Z INF Accepting connections on :8080 
2024-11-15T19:55:07Z DBG Finding container | id=ca3ecd7cb030
2024-11-15T19:55:07Z DBG Finding container | id=adf9cf51b463
2024-11-15T19:55:07Z DBG Finding container | id=f6e963e36db0
2024-11-15T19:55:07Z DBG Finding container | id=a896c2a527c1
2024-11-15T19:55:07Z DBG Finding container | id=c2a4568e3401
2024-11-15T19:55:07Z DBG Finding container | id=32bf6f159a37
2024-11-15T19:55:07Z DBG Finding container | id=0da2dcff9902
2024-11-15T19:55:07Z DBG Finding container | id=a9e50f367c66
2024-11-15T19:55:07Z DBG Finding container | id=d5830a201848
2024-11-15T19:55:07Z DBG Finding container | id=34cf1f7bbc5d
2024-11-15T19:55:07Z DBG Finding container | id=03bce6d57ee6
2024-11-15T19:55:07Z DBG Finding container | id=d9cb5ae0dea9
2024-11-15T19:55:07Z DBG Finding container | id=32fd1b920176
2024-11-15T19:55:07Z DBG Finding container | id=ff718a95cbf5
2024-11-15T19:55:07Z DBG Finding container | id=87122ba8174a
2024-11-15T19:55:07Z DBG Finding container | id=34cf1f7bbc5d
2024-11-15T19:55:07Z DBG Finding container | id=ca3ecd7cb030
2024-11-15T19:55:07Z DBG Finding container | id=87122ba8174a
2024-11-15T19:55:07Z DBG Finding container | id=03bce6d57ee6
2024-11-15T19:55:07Z DBG Finding container | id=32fd1b920176
2024-11-15T19:55:07Z DBG Finding container | id=adf9cf51b463
2024-11-15T19:55:07Z DBG Finding container | id=c2a4568e3401
2024-11-15T19:55:07Z DBG Finding container | id=32bf6f159a37
2024-11-15T19:55:07Z DBG Finding container | id=a896c2a527c1
2024-11-15T19:55:07Z DBG Finding container | id=a9e50f367c66
2024-11-15T19:55:07Z DBG Finding container | id=d5830a201848
2024-11-15T19:55:07Z DBG Finding container | id=d9cb5ae0dea9
2024-11-15T19:55:07Z DBG Finding container | id=f6e963e36db0
2024-11-15T19:55:07Z DBG Finding container | id=0da2dcff9902
2024-11-15T19:55:07Z DBG Finding container | id=ff718a95cbf5
2024-11-15T19:55:07Z DBG finished initializing container store | containers=15
2024-11-15T19:55:07Z DBG finished initializing container store | containers=15
2024-11-15T19:57:41Z DBG Fetching host | host=vcd1
2024-11-15T19:57:41Z DBG Fetching host | host=vcd1
2024-11-15T19:57:41Z DBG Fetching host | host=vcd1
2024-11-15T19:57:41Z DBG Cache hit | hit=false data=[]releases.Release
2024-11-15T19:57:48Z DBG Fetching host | host=vcd1
2024-11-15T19:57:48Z DBG Streaming logs for container | id=32fd1b920176 since=2024-11-15T19:55:06Z stdType=all host=vcd1
````

vcd2
````
2024-11-15T19:55:06Z INF Dozzle version pr-3394 
2024-11-15T19:55:06Z DBG Creating local client | filterArgs={}
2024-11-15T19:55:06Z DBG Fetching host | host=vcd2
2024-11-15T19:55:06Z DBG Finding container | id=c0412626d01d
2024-11-15T19:55:06Z DBG Listing containers | filter={} host=vcd2
2024-11-15T19:55:06Z DBG Fetching host | host=vcd2
2024-11-15T19:55:06Z DBG docker store subscribing docker events | host=vcd2
2024-11-15T19:55:06Z DBG found swarm service name | service=dozzle_dozzle
2024-11-15T19:55:06Z INF Starting in swarm mode 
2024-11-15T19:55:06Z DBG Using simple authentication 
2024-11-15T19:55:06Z DBG Fetching host | host=vcd2
2024-11-15T19:55:06Z DBG docker store subscribing docker events | host=vcd2
2024-11-15T19:55:06Z DBG Listing containers | filter={} host=vcd2
2024-11-15T19:55:06Z DBG Fetching host | host=vcd2
2024-11-15T19:55:06Z INF Dozzle agent version pr-3394 
2024-11-15T19:55:06Z DBG Finding container | id=894287cbd22f
2024-11-15T19:55:06Z DBG Finding container | id=cc0802012959
2024-11-15T19:55:06Z DBG Finding container | id=c0412626d01d
2024-11-15T19:55:06Z DBG Finding container | id=77391c79edfc
2024-11-15T19:55:06Z DBG Reading users.yml file | path=/data/users.yml
2024-11-15T19:55:06Z DBG finished initializing container store | containers=7
2024-11-15T19:55:06Z DBG Loaded users | users=1
2024-11-15T19:55:06Z DBG Finding container | id=894287cbd22f
2024-11-15T19:55:06Z DBG Finding container | id=cc0802012959
2024-11-15T19:55:06Z DBG Finding container | id=c0412626d01d
2024-11-15T19:55:06Z DBG Finding container | id=77391c79edfc
2024-11-15T19:55:06Z INF Accepting connections on :8080 
2024-11-15T19:55:06Z DBG finished initializing container store | containers=7
2024-11-15T19:57:41Z DBG Fetching host | host=vcd2
2024-11-15T19:57:41Z DBG Fetching host | host=vcd2
2024-11-15T19:57:48Z DBG Fetching host | host=vcd2
2024-11-15T19:57:48Z DBG found swarm service tasks | tasks.dozzle_dozzle=["10.88.6.3","10.88.6.4","10.88.6.5"] localIPs=["10.88.0.112","172.18.0.4","10.88.6.4"] clients.endpoints=["local"]
2024-11-15T19:57:48Z DBG Fetching host | host=vcd2
2024-11-15T19:57:48Z INF added new swarm agent | ip=10.88.6.3 id=bfbjsf12jdia1ilansubsrdc3 name=vcd3
2024-11-15T19:57:48Z DBG skipping local IP | ip=10.88.6.4
2024-11-15T19:57:48Z DBG Fetching host | host=vcd2
2024-11-15T19:57:48Z INF added new swarm agent | ip=10.88.6.5 id=14007tsydjyfsshmvxridz32a name=vcd1
2024-11-15T19:57:48Z DBG Streaming logs for container | id=c0412626d01d since=2024-11-15T19:55:06Z stdType=all host=vcd2
2024-11-15T19:58:50Z DBG runtime mem stats | allocated=3.6 MB totalAllocated=8.9 MB system=18 MB routines=48
````

vcd3
````
2024-11-15T19:55:06Z INF Dozzle version pr-3394 
2024-11-15T19:55:06Z DBG Creating local client | filterArgs={}
2024-11-15T19:55:06Z DBG Fetching host | host=vcd3
2024-11-15T19:55:06Z DBG Finding container | id=d54abb69a655
2024-11-15T19:55:06Z DBG Listing containers | filter={} host=vcd3
2024-11-15T19:55:06Z DBG Fetching host | host=vcd3
2024-11-15T19:55:06Z DBG docker store subscribing docker events | host=vcd3
2024-11-15T19:55:06Z DBG found swarm service name | service=dozzle_dozzle
2024-11-15T19:55:06Z INF Starting in swarm mode 
2024-11-15T19:55:06Z DBG Using simple authentication 
2024-11-15T19:55:06Z DBG Listing containers | filter={} host=vcd3
2024-11-15T19:55:06Z DBG Fetching host | host=vcd3
2024-11-15T19:55:06Z DBG docker store subscribing docker events | host=vcd3
2024-11-15T19:55:06Z DBG Fetching host | host=vcd3
2024-11-15T19:55:06Z INF Dozzle agent version pr-3394 
2024-11-15T19:55:06Z DBG Reading users.yml file | path=/data/users.yml
2024-11-15T19:55:06Z DBG Loaded users | users=1
2024-11-15T19:55:06Z INF Accepting connections on :8080 
2024-11-15T19:55:06Z DBG Finding container | id=c87e87055f74
2024-11-15T19:55:06Z DBG Finding container | id=d54abb69a655
2024-11-15T19:55:06Z DBG Finding container | id=a09067dbf8f0
2024-11-15T19:55:06Z DBG Finding container | id=8260b27f0ae7
2024-11-15T19:55:06Z DBG Finding container | id=1e197fed066d
2024-11-15T19:55:06Z DBG Finding container | id=350961c7f873
2024-11-15T19:55:06Z DBG Finding container | id=8c2ee6dabcaf
2024-11-15T19:55:06Z DBG Finding container | id=acd20752266c
2024-11-15T19:55:06Z DBG Finding container | id=8829f48724f4
2024-11-15T19:55:06Z DBG Finding container | id=d54abb69a655
2024-11-15T19:55:06Z DBG finished initializing container store | containers=9
2024-11-15T19:55:06Z DBG Finding container | id=a09067dbf8f0
2024-11-15T19:55:06Z DBG Finding container | id=8260b27f0ae7
2024-11-15T19:55:06Z DBG Finding container | id=350961c7f873
2024-11-15T19:55:06Z DBG Finding container | id=8c2ee6dabcaf
2024-11-15T19:55:06Z DBG Finding container | id=acd20752266c
2024-11-15T19:55:06Z DBG Finding container | id=1e197fed066d
2024-11-15T19:55:06Z DBG Finding container | id=8829f48724f4
2024-11-15T19:55:06Z DBG Finding container | id=c87e87055f74
2024-11-15T19:55:06Z DBG finished initializing container store | containers=9
2024-11-15T19:57:41Z DBG Listing containers | filter={} host=vcd3
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z DBG found swarm service tasks | tasks.dozzle_dozzle=["10.88.6.5","10.88.6.3","10.88.6.4"] localIPs=["10.88.0.111","172.18.0.4","10.88.6.3"] clients.endpoints=["local"]
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z DBG starting to stream stats | container=1e197fed066d host=vcd3
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z DBG starting to stream stats | container=acd20752266c host=vcd3
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z DBG starting to stream stats | container=8260b27f0ae7 host=vcd3
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z DBG starting to stream stats | container=350961c7f873 host=vcd3
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z DBG starting to stream stats | container=8c2ee6dabcaf host=vcd3
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z DBG starting to stream stats | container=8829f48724f4 host=vcd3
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z DBG starting to stream stats | container=c87e87055f74 host=vcd3
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z DBG starting to stream stats | container=d54abb69a655 host=vcd3
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z DBG starting to listen to docker events | host=vcd3
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z DBG starting to stream stats | container=a09067dbf8f0 host=vcd3
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z INF added new swarm agent | ip=10.88.6.5 id=14007tsydjyfsshmvxridz32a name=vcd1
2024-11-15T19:57:41Z DBG skipping local IP | ip=10.88.6.3
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:41Z INF added new swarm agent | ip=10.88.6.4 id=s81jgft1604jdqcjievlmxbza name=vcd2
2024-11-15T19:57:41Z DBG Fetching host | host=vcd3
2024-11-15T19:57:48Z DBG Fetching host | host=vcd3
2024-11-15T19:57:48Z DBG Streaming logs for container | id=d54abb69a655 since=2024-11-15T19:55:06Z stdType=all host=vcd3
````


Furthermore, I have confirmed for sure that the exact same remote agent works normally if I switch back to standalone:

````
environment:
     # - DOZZLE_MODE=swarm
deploy:
      #mode: global
      mode: replicated
      replicas: 1
````

**Comment by amir20** [comment] 2024-11-15 20:37
Thanks for testing. I think there is a mis-understanding. This issue is for remote agents. You are testing with `DOZZLE_REMOTE_HOST` which is a different code path. I don't plan to support this. I would suggest you move to Dozzle agents which uses `DOZZLE_REMOTE_AGENT`.  Remote hosts do not reconnect and more complicated. 

Also, I noticed your logs are not JSON. That seems odd since Dozzle should spit out a bunch of JSON logs. 

For now, this is issue is ONLY for agents.

**Comment by mitchplze** [comment] 2024-11-15 20:56
Wow! I didn't even realize there was an agent available. That actually saves a lot of hassle with the Proxy altogether. 

I just updated the `hs1` to use agent, and then updated Stack compose to: 

````
       
services:
  dozzle:
    # image: amir20/dozzle:latest
    image: amir20/dozzle:pr-3394
    environment:
      - DOZZLE_LEVEL=debug
      - DOZZLE_MODE=swarm
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_ENABLE_ACTIONS=true 
      # - DOZZLE_REMOTE_HOST=tcp://100.121.168.112:2375|hs1 
      - DOZZLE_REMOTE_AGENT=100.121.168.112:7007
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    ports:
      - "9999:8080"
    networks:
      - dozzle
    deploy:
      mode: global
      # mode: replicated
      # replicas: 1

networks:
  dozzle:
    driver: overlay

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.5.5,nolock,soft,rw
      device: :/volume1/docker/dozzle/data    
````

And it works great! The logo for `hs1` should be a regular host (not Swarm logo), but other than that I can't find any issues at all. I'll do some more testing today though and let you know once I get them all added in.

<img width="321" alt="image" src="https://github.com/user-attachments/assets/b272c0de-ec22-43ca-9b79-ef495d6b54ed">


RE: 

> Also, I noticed your logs are not JSON. That seems odd since Dozzle should spit out a bunch of JSON logs.

I actually ended up copy/pasting logs from Portainer. I couldn't figure out how to export or copy/paste the logs from Dozzle UI itself. There is no "Download" option for Swarm mode, only on individual hosts. I guess I could have checked that.

**Comment by amir20** [comment] 2024-11-15 21:00
> Wow! I didn't even realize there was an agent available. That actually saves a lot of hassle with the Proxy altogether.

🙌🏼 that's the hope. I got so many bugs with proxy that I just gave up. 

> And it works great! The logo for hs1 should be a regular host (not Swarm logo), but other than that I can't find any issues at all. I'll do some more testing today though and let you know once I get them all added in

That's awesome. Then I wonder why it's not working for me. It must be a routing error on my local set up. 

> I actually ended up copy/pasting logs from Portainer. I couldn't figure out how to export or copy/paste the logs from Dozzle UI itself. There is no "Download" option for Swarm mode, only on individual hosts. I guess I could have checked that.

Ok that makes sense more. Services can't scroll up, but I guess download should work. The reason I didn't do it is that all containers in a service emit logs at different time. Which means I would have to collect all, and then sort. I guess I won't get to this for a while.

**Comment by mitchplze** [comment] 2024-11-15 21:32
> That's awesome. Then I wonder why it's not working for me. It must be a routing error on my local set up.

I'm cheating, and I just use Tailscale IP addresses. Makes it way too easy. I simply add `tag:docker` to each of my hosts, and then I have an ACL rule: 

````
{
	"action": "accept", // Allow traffic
	"src":    ["tag:docker"], // from Docker servers
	"dst":    ["tag:docker:1337,8080,9443,9001,45876,9005,7007"], // Docker socket, a couple other tools, and Dozzle Agent now!
},
````

-----

> Ok that makes sense more. Services can't scroll up, but I guess download should work. The reason I didn't do it is that all containers in a service emit logs at different time.

I might put in another feature req for this, but it would probably help if there was a `Show hostnames` radio button (and feature) on the below screen. The colour coding is a great start for Swarm mode, but having the actual node name available in log view would be very helpful.

<img width="557" alt="image" src="https://github.com/user-attachments/assets/ae7a2445-844c-4f89-8752-ce18f50306d6">

<img width="323" alt="image" src="https://github.com/user-attachments/assets/13c4bbad-3793-44c7-b701-6e725dd1aee3">

**Comment by amir20** [comment] 2024-11-15 21:47
🤦🏼 I was using the wrong port. `198.19.248.6:7070` instead of `198.19.248.6:7007`. 

It seems to be working now. 

I see the broken icons too. I'll have to come back to this next week.

**Comment by mitchplze** [comment] 2024-11-15 21:49
@amir20: This feature is a thing of beauty and seems to be working great! Thank you so much. 

- I'm not clear why there are yellow version flags on some hosts. (Everything except the Swarm (`:pr-3394`) is running `:latest` pulled from this morning)
- Not sure why some of them have different icons altogether now. All are using 7007 agent method now, except the Swarm itself.

<img width="1493" alt="image" src="https://github.com/user-attachments/assets/017e8546-9f84-4bbf-b076-9a3a05b3ada4">

**Comment by mitchplze** [comment] 2024-11-15 21:50
> 🤦🏼 I was using the wrong port. `198.19.248.6:7070` instead of `198.19.248.6:7007`.
> 
> It seems to be working now.

😂 I actually also did the same thing with 7070 this morning and was head scratching for more than a minute.

> I see the broken icons too. I'll have to come back to this next week.

Thanks again seriously. Great project.

**Comment by amir20** [comment] 2024-11-15 22:46
> Not sure why some of them have different icons altogether now. All are using 7007 agent method now, except the Swarm itself.

Icons should be fixed now. 

> I'm not clear why there are yellow version flags on some hosts. (Everything except the Swarm (:pr-3394) is running :latest pulled from this morning)

The versions don't match so that is why it is yellow. I don't really treat PRs with a special condition.

**Comment by amir20** [comment] 2024-11-16 23:37
The PR looks good. I have merged it. Going to release a minor version soon.

**Closed** 2024-11-16 23:38 UTC
Labels: enhancement
